#import "IFDripicons.h"

@implementation IFDripicons

+ (NSURL *)fontFileURL
{
    return [[[NSBundle mainBundle] resourceURL] URLByAppendingPathComponent:@"dripicons.ttf"];
}

+ (NSDictionary *)allIcons
{
    return @{
             @"icon-align-center":                       @"\ue000",
             @"icon-align-justify":                      @"\ue001",
             @"icon-align-left":                         @"\ue002",
             @"icon-align-right":                        @"\ue003",
             @"icon-arrow-down":                         @"\ue004",
             @"icon-arrow-left":                         @"\ue005",
             @"icon-arrow-thin-down":                    @"\ue006",
             @"icon-arrow-right":                        @"\ue007",
             @"icon-arrow-thin-left":                    @"\ue008",
             @"icon-arrow-thin-up":                      @"\ue009",
             @"icon-arrow-up":                           @"\ue010",
             @"icon-attachment":                         @"\ue011",
             @"icon-arrow-thin-right":                   @"\ue012",
             @"icon-code":                               @"\ue013",
             @"icon-cloud":                              @"\ue014",
             @"icon-chevron-right":                      @"\ue015",
             @"icon-chevron-up":                         @"\ue016",
             @"icon-chevron-down":                       @"\ue017",
             @"icon-chevron-left":                       @"\ue018",
             @"icon-camera":                             @"\ue019",
             @"icon-checkmark":                          @"\ue020",
             @"icon-calendar":                           @"\ue021",
             @"icon-clockwise":                          @"\ue022",
             @"icon-conversation":                       @"\ue023",
             @"icon-direction":                          @"\ue024",
             @"icon-cross":                              @"\ue025",
             @"icon-graph-line":                         @"\ue026",
             @"icon-gear":                               @"\ue027",
             @"icon-graph-bar":                          @"\ue028",
             @"icon-export":                             @"\ue029",
             @"icon-feed":                               @"\ue030",
             @"icon-folder":                             @"\ue031",
             @"icon-forward":                            @"\ue032",
             @"icon-folder-open":                        @"\ue033",
             @"icon-download":                           @"\ue034",
             @"icon-document-new":                       @"\ue035",
             @"icon-document-edit":                      @"\ue036",
             @"icon-document":                           @"\ue037",
             @"icon-gaming":                             @"\ue038",
             @"icon-graph-pie":                          @"\ue039",
             @"icon-heart":                              @"\ue040",
             @"icon-headset":                            @"\ue041",
             @"icon-help":                               @"\ue042",
             @"icon-information":                        @"\ue043",
             @"icon-loading":                            @"\ue044",
             @"icon-lock":                               @"\ue045",
             @"icon-location":                           @"\ue046",
             @"icon-lock-open":                          @"\ue047",
             @"icon-mail":                               @"\ue048",
             @"icon-map":                                @"\ue049",
             @"icon-media-loop":                         @"\ue050",
             @"icon-mobile-portrait":                    @"\ue051",
             @"icon-mobile-landscape":                   @"\ue052",
             @"icon-microphone":                         @"\ue053",
             @"icon-minus":                              @"\ue054",
             @"icon-message":                            @"\ue055",
             @"icon-menu":                               @"\ue056",
             @"icon-media-stop":                         @"\ue057",
             @"icon-media-shuffle":                      @"\ue058",
             @"icon-media-previous":                     @"\ue059",
             @"icon-media-play":                         @"\ue060",
             @"icon-media-next":                         @"\ue061",
             @"icon-media-pause":                        @"\ue062",
             @"icon-monitor":                            @"\ue063",
             @"icon-move":                               @"\ue064",
             @"icon-plus":                               @"\ue065",
             @"icon-phone":                              @"\ue066",
             @"icon-preview":                            @"\ue067",
             @"icon-print":                              @"\ue068",
             @"icon-media-record":                       @"\ue069",
             @"icon-music":                              @"\ue070",
             @"icon-home":                               @"\ue071",
             @"icon-question":                           @"\ue072",
             @"icon-reply":                              @"\ue073",
             @"icon-reply-all":                          @"\ue074",
             @"icon-return":                             @"\ue075",
             @"icon-retweet":                            @"\ue076",
             @"icon-search":                             @"\ue077",
             @"icon-view-thumb":                         @"\ue078",
             @"icon-view-list-large":                    @"\ue079",
             @"icon-view-list":                          @"\ue080",
             @"icon-upload":                             @"\ue081",
             @"icon-user-group":                         @"\ue082",
             @"icon-trash":                              @"\ue083",
             @"icon-user":                               @"\ue084",
             @"icon-thumbs-up":                          @"\ue085",
             @"icon-thumbs-down":                        @"\ue086",
             @"icon-tablet-portrait":                    @"\ue087",
             @"icon-tablet-landscape":                   @"\ue088",
             @"icon-tag":                                @"\ue089",
             @"icon-star":                               @"\ue090",
             @"icon-volume-full":                        @"\ue091",
             @"icon-volume-off":                         @"\ue092",
             @"icon-warning":                            @"\ue093",
             @"icon-window":                             @"\ue094",
             };
}

@end
