#import <IconFontsKit/IFIcon.h>

/// Genericons icon types.
typedef NS_ENUM(IFIconType, IFGenericonsType) {
    /// Identifier: "genericon-404"
    IFGenericons404                                 = 0xf423,
    /// Identifier: "genericon-activity"
    IFGenericonsActivity                            = 0xf508,
    /// Identifier: "genericon-anchor"
    IFGenericonsAnchor                              = 0xf509,
    /// Identifier: "genericon-aside"
    IFGenericonsAside                               = 0xf101,
    /// Identifier: "genericon-attachment"
    IFGenericonsAttachment                          = 0xf416,
    /// Identifier: "genericon-audio"
    IFGenericonsAudio                               = 0xf109,
    /// Identifier: "genericon-bold"
    IFGenericonsBold                                = 0xf471,
    /// Identifier: "genericon-book"
    IFGenericonsBook                                = 0xf444,
    /// Identifier: "genericon-bug"
    IFGenericonsBug                                 = 0xf50a,
    /// Identifier: "genericon-cart"
    IFGenericonsCart                                = 0xf447,
    /// Identifier: "genericon-category"
    IFGenericonsCategory                            = 0xf301,
    /// Identifier: "genericon-chat"
    IFGenericonsChat                                = 0xf108,
    /// Identifier: "genericon-checkmark"
    IFGenericonsCheckmark                           = 0xf418,
    /// Identifier: "genericon-close"
    IFGenericonsClose                               = 0xf405,
    /// Identifier: "genericon-close-alt"
    IFGenericonsCloseAlt                            = 0xf406,
    /// Identifier: "genericon-cloud"
    IFGenericonsCloud                               = 0xf426,
    /// Identifier: "genericon-cloud-download"
    IFGenericonsCloudDownload                       = 0xf440,
    /// Identifier: "genericon-cloud-upload"
    IFGenericonsCloudUpload                         = 0xf441,
    /// Identifier: "genericon-code"
    IFGenericonsCode                                = 0xf462,
    /// Identifier: "genericon-codepen"
    IFGenericonsCodepen                             = 0xf216,
    /// Identifier: "genericon-cog"
    IFGenericonsCog                                 = 0xf445,
    /// Identifier: "genericon-collapse"
    IFGenericonsCollapse                            = 0xf432,
    /// Identifier: "genericon-comment"
    IFGenericonsComment                             = 0xf300,
    /// Identifier: "genericon-day"
    IFGenericonsDay                                 = 0xf305,
    /// Identifier: "genericon-digg"
    IFGenericonsDigg                                = 0xf221,
    /// Identifier: "genericon-document"
    IFGenericonsDocument                            = 0xf443,
    /// Identifier: "genericon-dot"
    IFGenericonsDot                                 = 0xf428,
    /// Identifier: "genericon-downarrow"
    IFGenericonsDownarrow                           = 0xf502,
    /// Identifier: "genericon-download"
    IFGenericonsDownload                            = 0xf50b,
    /// Identifier: "genericon-draggable"
    IFGenericonsDraggable                           = 0xf436,
    /// Identifier: "genericon-dribbble"
    IFGenericonsDribbble                            = 0xf201,
    /// Identifier: "genericon-dropbox"
    IFGenericonsDropbox                             = 0xf225,
    /// Identifier: "genericon-dropdown"
    IFGenericonsDropdown                            = 0xf433,
    /// Identifier: "genericon-dropdown-left"
    IFGenericonsDropdownLeft                        = 0xf434,
    /// Identifier: "genericon-edit"
    IFGenericonsEdit                                = 0xf411,
    /// Identifier: "genericon-ellipsis"
    IFGenericonsEllipsis                            = 0xf476,
    /// Identifier: "genericon-expand"
    IFGenericonsExpand                              = 0xf431,
    /// Identifier: "genericon-external"
    IFGenericonsExternal                            = 0xf442,
    /// Identifier: "genericon-facebook"
    IFGenericonsFacebook                            = 0xf203,
    /// Identifier: "genericon-facebook-alt"
    IFGenericonsFacebookAlt                         = 0xf204,
    /// Identifier: "genericon-fastforward"
    IFGenericonsFastforward                         = 0xf458,
    /// Identifier: "genericon-feed"
    IFGenericonsFeed                                = 0xf413,
    /// Identifier: "genericon-flag"
    IFGenericonsFlag                                = 0xf468,
    /// Identifier: "genericon-flickr"
    IFGenericonsFlickr                              = 0xf211,
    /// Identifier: "genericon-foursquare"
    IFGenericonsFoursquare                          = 0xf226,
    /// Identifier: "genericon-fullscreen"
    IFGenericonsFullscreen                          = 0xf474,
    /// Identifier: "genericon-gallery"
    IFGenericonsGallery                             = 0xf103,
    /// Identifier: "genericon-github"
    IFGenericonsGithub                              = 0xf200,
    /// Identifier: "genericon-googleplus"
    IFGenericonsGoogleplus                          = 0xf206,
    /// Identifier: "genericon-googleplus-alt"
    IFGenericonsGoogleplusAlt                       = 0xf218,
    /// Identifier: "genericon-handset"
    IFGenericonsHandset                             = 0xf50c,
    /// Identifier: "genericon-heart"
    IFGenericonsHeart                               = 0xf461,
    /// Identifier: "genericon-help"
    IFGenericonsHelp                                = 0xf457,
    /// Identifier: "genericon-hide"
    IFGenericonsHide                                = 0xf404,
    /// Identifier: "genericon-hierarchy"
    IFGenericonsHierarchy                           = 0xf505,
    /// Identifier: "genericon-home"
    IFGenericonsHome                                = 0xf409,
    /// Identifier: "genericon-image"
    IFGenericonsImage                               = 0xf102,
    /// Identifier: "genericon-info"
    IFGenericonsInfo                                = 0xf455,
    /// Identifier: "genericon-instagram"
    IFGenericonsInstagram                           = 0xf215,
    /// Identifier: "genericon-italic"
    IFGenericonsItalic                              = 0xf472,
    /// Identifier: "genericon-key"
    IFGenericonsKey                                 = 0xf427,
    /// Identifier: "genericon-leftarrow"
    IFGenericonsLeftarrow                           = 0xf503,
    /// Identifier: "genericon-link"
    IFGenericonsLink                                = 0xf107,
    /// Identifier: "genericon-linkedin"
    IFGenericonsLinkedin                            = 0xf207,
    /// Identifier: "genericon-linkedin-alt"
    IFGenericonsLinkedinAlt                         = 0xf208,
    /// Identifier: "genericon-location"
    IFGenericonsLocation                            = 0xf417,
    /// Identifier: "genericon-lock"
    IFGenericonsLock                                = 0xf470,
    /// Identifier: "genericon-mail"
    IFGenericonsMail                                = 0xf410,
    /// Identifier: "genericon-maximize"
    IFGenericonsMaximize                            = 0xf422,
    /// Identifier: "genericon-menu"
    IFGenericonsMenu                                = 0xf419,
    /// Identifier: "genericon-microphone"
    IFGenericonsMicrophone                          = 0xf50d,
    /// Identifier: "genericon-minimize"
    IFGenericonsMinimize                            = 0xf421,
    /// Identifier: "genericon-minus"
    IFGenericonsMinus                               = 0xf50e,
    /// Identifier: "genericon-month"
    IFGenericonsMonth                               = 0xf307,
    /// Identifier: "genericon-move"
    IFGenericonsMove                                = 0xf50f,
    /// Identifier: "genericon-next"
    IFGenericonsNext                                = 0xf429,
    /// Identifier: "genericon-notice"
    IFGenericonsNotice                              = 0xf456,
    /// Identifier: "genericon-paintbrush"
    IFGenericonsPaintbrush                          = 0xf506,
    /// Identifier: "genericon-path"
    IFGenericonsPath                                = 0xf219,
    /// Identifier: "genericon-pause"
    IFGenericonsPause                               = 0xf448,
    /// Identifier: "genericon-phone"
    IFGenericonsPhone                               = 0xf437,
    /// Identifier: "genericon-picture"
    IFGenericonsPicture                             = 0xf473,
    /// Identifier: "genericon-pinned"
    IFGenericonsPinned                              = 0xf308,
    /// Identifier: "genericon-pinterest"
    IFGenericonsPinterest                           = 0xf209,
    /// Identifier: "genericon-pinterest-alt"
    IFGenericonsPinterestAlt                        = 0xf210,
    /// Identifier: "genericon-play"
    IFGenericonsPlay                                = 0xf452,
    /// Identifier: "genericon-plugin"
    IFGenericonsPlugin                              = 0xf439,
    /// Identifier: "genericon-plus"
    IFGenericonsPlus                                = 0xf510,
    /// Identifier: "genericon-pocket"
    IFGenericonsPocket                              = 0xf224,
    /// Identifier: "genericon-polldaddy"
    IFGenericonsPolldaddy                           = 0xf217,
    /// Identifier: "genericon-portfolio"
    IFGenericonsPortfolio                           = 0xf460,
    /// Identifier: "genericon-previous"
    IFGenericonsPrevious                            = 0xf430,
    /// Identifier: "genericon-print"
    IFGenericonsPrint                               = 0xf469,
    /// Identifier: "genericon-quote"
    IFGenericonsQuote                               = 0xf106,
    /// Identifier: "genericon-rating-empty"
    IFGenericonsRatingEmpty                         = 0xf511,
    /// Identifier: "genericon-rating-full"
    IFGenericonsRatingFull                          = 0xf512,
    /// Identifier: "genericon-rating-half"
    IFGenericonsRatingHalf                          = 0xf513,
    /// Identifier: "genericon-reddit"
    IFGenericonsReddit                              = 0xf222,
    /// Identifier: "genericon-refresh"
    IFGenericonsRefresh                             = 0xf420,
    /// Identifier: "genericon-reply"
    IFGenericonsReply                               = 0xf412,
    /// Identifier: "genericon-reply-alt"
    IFGenericonsReplyAlt                            = 0xf466,
    /// Identifier: "genericon-reply-single"
    IFGenericonsReplySingle                         = 0xf467,
    /// Identifier: "genericon-rewind"
    IFGenericonsRewind                              = 0xf459,
    /// Identifier: "genericon-rightarrow"
    IFGenericonsRightarrow                          = 0xf501,
    /// Identifier: "genericon-search"
    IFGenericonsSearch                              = 0xf400,
    /// Identifier: "genericon-send-to-phone"
    IFGenericonsSendToPhone                         = 0xf438,
    /// Identifier: "genericon-send-to-tablet"
    IFGenericonsSendToTablet                        = 0xf454,
    /// Identifier: "genericon-share"
    IFGenericonsShare                               = 0xf415,
    /// Identifier: "genericon-show"
    IFGenericonsShow                                = 0xf403,
    /// Identifier: "genericon-shuffle"
    IFGenericonsShuffle                             = 0xf514,
    /// Identifier: "genericon-sitemap"
    IFGenericonsSitemap                             = 0xf507,
    /// Identifier: "genericon-skip-ahead"
    IFGenericonsSkipAhead                           = 0xf451,
    /// Identifier: "genericon-skip-back"
    IFGenericonsSkipBack                            = 0xf450,
    /// Identifier: "genericon-skype"
    IFGenericonsSkype                               = 0xf220,
    /// Identifier: "genericon-spam"
    IFGenericonsSpam                                = 0xf424,
    /// Identifier: "genericon-spotify"
    IFGenericonsSpotify                             = 0xf515,
    /// Identifier: "genericon-standard"
    IFGenericonsStandard                            = 0xf100,
    /// Identifier: "genericon-star"
    IFGenericonsStar                                = 0xf408,
    /// Identifier: "genericon-status"
    IFGenericonsStatus                              = 0xf105,
    /// Identifier: "genericon-stop"
    IFGenericonsStop                                = 0xf449,
    /// Identifier: "genericon-stumbleupon"
    IFGenericonsStumbleupon                         = 0xf223,
    /// Identifier: "genericon-subscribe"
    IFGenericonsSubscribe                           = 0xf463,
    /// Identifier: "genericon-subscribed"
    IFGenericonsSubscribed                          = 0xf465,
    /// Identifier: "genericon-summary"
    IFGenericonsSummary                             = 0xf425,
    /// Identifier: "genericon-tablet"
    IFGenericonsTablet                              = 0xf453,
    /// Identifier: "genericon-tag"
    IFGenericonsTag                                 = 0xf302,
    /// Identifier: "genericon-time"
    IFGenericonsTime                                = 0xf303,
    /// Identifier: "genericon-top"
    IFGenericonsTop                                 = 0xf435,
    /// Identifier: "genericon-trash"
    IFGenericonsTrash                               = 0xf407,
    /// Identifier: "genericon-tumblr"
    IFGenericonsTumblr                              = 0xf214,
    /// Identifier: "genericon-twitch"
    IFGenericonsTwitch                              = 0xf516,
    /// Identifier: "genericon-twitter"
    IFGenericonsTwitter                             = 0xf202,
    /// Identifier: "genericon-unapprove"
    IFGenericonsUnapprove                           = 0xf446,
    /// Identifier: "genericon-unsubscribe"
    IFGenericonsUnsubscribe                         = 0xf464,
    /// Identifier: "genericon-unzoom"
    IFGenericonsUnzoom                              = 0xf401,
    /// Identifier: "genericon-uparrow"
    IFGenericonsUparrow                             = 0xf500,
    /// Identifier: "genericon-user"
    IFGenericonsUser                                = 0xf304,
    /// Identifier: "genericon-video"
    IFGenericonsVideo                               = 0xf104,
    /// Identifier: "genericon-videocamera"
    IFGenericonsVideocamera                         = 0xf517,
    /// Identifier: "genericon-vimeo"
    IFGenericonsVimeo                               = 0xf212,
    /// Identifier: "genericon-warning"
    IFGenericonsWarning                             = 0xf414,
    /// Identifier: "genericon-website"
    IFGenericonsWebsite                             = 0xf475,
    /// Identifier: "genericon-week"
    IFGenericonsWeek                                = 0xf306,
    /// Identifier: "genericon-wordpress"
    IFGenericonsWordpress                           = 0xf205,
    /// Identifier: "genericon-xpost"
    IFGenericonsXpost                               = 0xf504,
    /// Identifier: "genericon-youtube"
    IFGenericonsYoutube                             = 0xf213,
    /// Identifier: "genericon-zoom"
    IFGenericonsZoom                                = 0xf402,
};

/*!
 * Genericons v3.4.1 http://genericons.com
 */
@interface IFGenericons : IFIcon
@end
