#import <IconFontsKit/IFIcon.h>

/// MapIcons icon types.
typedef NS_ENUM(IFIconType, IFMapIconsType) {
    /// Identifier: "map-icon-abseiling"
    IFMapIconsAbseiling                           = 0xe800,
    /// Identifier: "map-icon-accounting"
    IFMapIconsAccounting                          = 0xe801,
    /// Identifier: "map-icon-airport"
    IFMapIconsAirport                             = 0xe802,
    /// Identifier: "map-icon-amusement-park"
    IFMapIconsAmusementPark                       = 0xe803,
    /// Identifier: "map-icon-aquarium"
    IFMapIconsAquarium                            = 0xe804,
    /// Identifier: "map-icon-archery"
    IFMapIconsArchery                             = 0xe805,
    /// Identifier: "map-icon-art-gallery"
    IFMapIconsArtGallery                          = 0xe806,
    /// Identifier: "map-icon-assistive-listening-system"
    IFMapIconsAssistiveListeningSystem            = 0xe807,
    /// Identifier: "map-icon-atm"
    IFMapIconsAtm                                 = 0xe808,
    /// Identifier: "map-icon-audio-description"
    IFMapIconsAudioDescription                    = 0xe809,
    /// Identifier: "map-icon-bakery"
    IFMapIconsBakery                              = 0xe80a,
    /// Identifier: "map-icon-bank"
    IFMapIconsBank                                = 0xe80b,
    /// Identifier: "map-icon-bar"
    IFMapIconsBar                                 = 0xe80c,
    /// Identifier: "map-icon-baseball"
    IFMapIconsBaseball                            = 0xe80d,
    /// Identifier: "map-icon-beauty-salon"
    IFMapIconsBeautySalon                         = 0xe80e,
    /// Identifier: "map-icon-bicycle-store"
    IFMapIconsBicycleStore                        = 0xe80f,
    /// Identifier: "map-icon-bicycling"
    IFMapIconsBicycling                           = 0xe810,
    /// Identifier: "map-icon-boat-ramp"
    IFMapIconsBoatRamp                            = 0xe811,
    /// Identifier: "map-icon-boat-tour"
    IFMapIconsBoatTour                            = 0xe812,
    /// Identifier: "map-icon-boating"
    IFMapIconsBoating                             = 0xe813,
    /// Identifier: "map-icon-book-store"
    IFMapIconsBookStore                           = 0xe814,
    /// Identifier: "map-icon-bowling-alley"
    IFMapIconsBowlingAlley                        = 0xe815,
    /// Identifier: "map-icon-braille"
    IFMapIconsBraille                             = 0xe816,
    /// Identifier: "map-icon-bus-station"
    IFMapIconsBusStation                          = 0xe817,
    /// Identifier: "map-icon-cafe"
    IFMapIconsCafe                                = 0xe818,
    /// Identifier: "map-icon-campground"
    IFMapIconsCampground                          = 0xe819,
    /// Identifier: "map-icon-canoe"
    IFMapIconsCanoe                               = 0xe81a,
    /// Identifier: "map-icon-car-dealer"
    IFMapIconsCarDealer                           = 0xe81b,
    /// Identifier: "map-icon-car-rental"
    IFMapIconsCarRental                           = 0xe81c,
    /// Identifier: "map-icon-car-repair"
    IFMapIconsCarRepair                           = 0xe81d,
    /// Identifier: "map-icon-car-wash"
    IFMapIconsCarWash                             = 0xe81e,
    /// Identifier: "map-icon-casino"
    IFMapIconsCasino                              = 0xe81f,
    /// Identifier: "map-icon-cemetery"
    IFMapIconsCemetery                            = 0xe820,
    /// Identifier: "map-icon-chairlift"
    IFMapIconsChairlift                           = 0xe821,
    /// Identifier: "map-icon-church"
    IFMapIconsChurch                              = 0xe822,
    /// Identifier: "map-icon-circle"
    IFMapIconsCircle                              = 0xe823,
    /// Identifier: "map-icon-city-hall"
    IFMapIconsCityHall                            = 0xe824,
    /// Identifier: "map-icon-climbing"
    IFMapIconsClimbing                            = 0xe825,
    /// Identifier: "map-icon-closed-captioning"
    IFMapIconsClosedCaptioning                    = 0xe826,
    /// Identifier: "map-icon-clothing-store"
    IFMapIconsClothingStore                       = 0xe827,
    /// Identifier: "map-icon-compass"
    IFMapIconsCompass                             = 0xe828,
    /// Identifier: "map-icon-convenience-store"
    IFMapIconsConvenienceStore                    = 0xe829,
    /// Identifier: "map-icon-courthouse"
    IFMapIconsCourthouse                          = 0xe82a,
    /// Identifier: "map-icon-cross-country-skiing"
    IFMapIconsCrossCountrySkiing                  = 0xe82b,
    /// Identifier: "map-icon-crosshairs"
    IFMapIconsCrosshairs                          = 0xe82c,
    /// Identifier: "map-icon-dentist"
    IFMapIconsDentist                             = 0xe82d,
    /// Identifier: "map-icon-department-store"
    IFMapIconsDepartmentStore                     = 0xe82e,
    /// Identifier: "map-icon-diving"
    IFMapIconsDiving                              = 0xe82f,
    /// Identifier: "map-icon-doctor"
    IFMapIconsDoctor                              = 0xe830,
    /// Identifier: "map-icon-electrician"
    IFMapIconsElectrician                         = 0xe831,
    /// Identifier: "map-icon-electronics-store"
    IFMapIconsElectronicsStore                    = 0xe832,
    /// Identifier: "map-icon-embassy"
    IFMapIconsEmbassy                             = 0xe833,
    /// Identifier: "map-icon-expand"
    IFMapIconsExpand                              = 0xe834,
    /// Identifier: "map-icon-female"
    IFMapIconsFemale                              = 0xe835,
    /// Identifier: "map-icon-finance"
    IFMapIconsFinance                             = 0xe836,
    /// Identifier: "map-icon-fire-station"
    IFMapIconsFireStation                         = 0xe837,
    /// Identifier: "map-icon-fish-cleaning"
    IFMapIconsFishCleaning                        = 0xe838,
    /// Identifier: "map-icon-fishing-pier"
    IFMapIconsFishingPier                         = 0xe839,
    /// Identifier: "map-icon-fishing"
    IFMapIconsFishing                             = 0xe83a,
    /// Identifier: "map-icon-florist"
    IFMapIconsFlorist                             = 0xe83b,
    /// Identifier: "map-icon-food"
    IFMapIconsFood                                = 0xe83c,
    /// Identifier: "map-icon-fullscreen"
    IFMapIconsFullscreen                          = 0xe83d,
    /// Identifier: "map-icon-funeral-home"
    IFMapIconsFuneralHome                         = 0xe83e,
    /// Identifier: "map-icon-furniture-store"
    IFMapIconsFurnitureStore                      = 0xe83f,
    /// Identifier: "map-icon-gas-station"
    IFMapIconsGasStation                          = 0xe840,
    /// Identifier: "map-icon-general-contractor"
    IFMapIconsGeneralContractor                   = 0xe841,
    /// Identifier: "map-icon-golf"
    IFMapIconsGolf                                = 0xe842,
    /// Identifier: "map-icon-grocery-or-supermarket"
    IFMapIconsGroceryOrSupermarket                = 0xe843,
    /// Identifier: "map-icon-gym"
    IFMapIconsGym                                 = 0xe844,
    /// Identifier: "map-icon-hair-care"
    IFMapIconsHairCare                            = 0xe845,
    /// Identifier: "map-icon-hang-gliding"
    IFMapIconsHangGliding                         = 0xe846,
    /// Identifier: "map-icon-hardware-store"
    IFMapIconsHardwareStore                       = 0xe847,
    /// Identifier: "map-icon-health"
    IFMapIconsHealth                              = 0xe848,
    /// Identifier: "map-icon-hindu-temple"
    IFMapIconsHinduTemple                         = 0xe849,
    /// Identifier: "map-icon-horse-riding"
    IFMapIconsHorseRiding                         = 0xe84a,
    /// Identifier: "map-icon-hospital"
    IFMapIconsHospital                            = 0xe84b,
    /// Identifier: "map-icon-ice-fishing"
    IFMapIconsIceFishing                          = 0xe84c,
    /// Identifier: "map-icon-ice-skating"
    IFMapIconsIceSkating                          = 0xe84d,
    /// Identifier: "map-icon-inline-skating"
    IFMapIconsInlineSkating                       = 0xe84e,
    /// Identifier: "map-icon-insurance-agency"
    IFMapIconsInsuranceAgency                     = 0xe84f,
    /// Identifier: "map-icon-jet-skiing"
    IFMapIconsJetSkiing                           = 0xe850,
    /// Identifier: "map-icon-jewelry-store"
    IFMapIconsJewelryStore                        = 0xe851,
    /// Identifier: "map-icon-kayaking"
    IFMapIconsKayaking                            = 0xe852,
    /// Identifier: "map-icon-laundry"
    IFMapIconsLaundry                             = 0xe853,
    /// Identifier: "map-icon-lawyer"
    IFMapIconsLawyer                              = 0xe854,
    /// Identifier: "map-icon-library"
    IFMapIconsLibrary                             = 0xe855,
    /// Identifier: "map-icon-liquor-store"
    IFMapIconsLiquorStore                         = 0xe856,
    /// Identifier: "map-icon-local-government"
    IFMapIconsLocalGovernment                     = 0xe857,
    /// Identifier: "map-icon-location-arrow"
    IFMapIconsLocationArrow                       = 0xe858,
    /// Identifier: "map-icon-locksmith"
    IFMapIconsLocksmith                           = 0xe859,
    /// Identifier: "map-icon-lodging"
    IFMapIconsLodging                             = 0xe85a,
    /// Identifier: "map-icon-low-vision-access"
    IFMapIconsLowVisionAccess                     = 0xe85b,
    /// Identifier: "map-icon-male"
    IFMapIconsMale                                = 0xe85c,
    /// Identifier: "map-icon-map-pin"
    IFMapIconsMapPin                              = 0xe85d,
    /// Identifier: "map-icon-marina"
    IFMapIconsMarina                              = 0xe85e,
    /// Identifier: "map-icon-mosque"
    IFMapIconsMosque                              = 0xe85f,
    /// Identifier: "map-icon-motobike-trail"
    IFMapIconsMotobikeTrail                       = 0xe860,
    /// Identifier: "map-icon-movie-rental"
    IFMapIconsMovieRental                         = 0xe861,
    /// Identifier: "map-icon-movie-theater"
    IFMapIconsMovieTheater                        = 0xe862,
    /// Identifier: "map-icon-moving-company"
    IFMapIconsMovingCompany                       = 0xe863,
    /// Identifier: "map-icon-museum"
    IFMapIconsMuseum                              = 0xe864,
    /// Identifier: "map-icon-natural-feature"
    IFMapIconsNaturalFeature                      = 0xe865,
    /// Identifier: "map-icon-night-club"
    IFMapIconsNightClub                           = 0xe866,
    /// Identifier: "map-icon-open-captioning"
    IFMapIconsOpenCaptioning                      = 0xe867,
    /// Identifier: "map-icon-painter"
    IFMapIconsPainter                             = 0xe868,
    /// Identifier: "map-icon-park"
    IFMapIconsPark                                = 0xe869,
    /// Identifier: "map-icon-parking"
    IFMapIconsParking                             = 0xe86a,
    /// Identifier: "map-icon-pet-store"
    IFMapIconsPetStore                            = 0xe86b,
    /// Identifier: "map-icon-pharmacy"
    IFMapIconsPharmacy                            = 0xe86c,
    /// Identifier: "map-icon-physiotherapist"
    IFMapIconsPhysiotherapist                     = 0xe86d,
    /// Identifier: "map-icon-place-of-worship"
    IFMapIconsPlaceOfWorship                      = 0xe86e,
    /// Identifier: "map-icon-playground"
    IFMapIconsPlayground                          = 0xe86f,
    /// Identifier: "map-icon-plumber"
    IFMapIconsPlumber                             = 0xe870,
    /// Identifier: "map-icon-point-of-interest"
    IFMapIconsPointOfInterest                     = 0xe871,
    /// Identifier: "map-icon-police"
    IFMapIconsPolice                              = 0xe872,
    /// Identifier: "map-icon-political"
    IFMapIconsPolitical                           = 0xe873,
    /// Identifier: "map-icon-post-box"
    IFMapIconsPostBox                             = 0xe874,
    /// Identifier: "map-icon-post-office"
    IFMapIconsPostOffice                          = 0xe875,
    /// Identifier: "map-icon-postal-code-prefix"
    IFMapIconsPostalCodePrefix                    = 0xe876,
    /// Identifier: "map-icon-postal-code"
    IFMapIconsPostalCode                          = 0xe877,
    /// Identifier: "map-icon-rafting"
    IFMapIconsRafting                             = 0xe878,
    /// Identifier: "map-icon-real-estate-agency"
    IFMapIconsRealEstateAgency                    = 0xe879,
    /// Identifier: "map-icon-restaurant"
    IFMapIconsRestaurant                          = 0xe87a,
    /// Identifier: "map-icon-roofing-contractor"
    IFMapIconsRoofingContractor                   = 0xe87b,
    /// Identifier: "map-icon-route-pin"
    IFMapIconsRoutePin                            = 0xe87c,
    /// Identifier: "map-icon-route"
    IFMapIconsRoute                               = 0xe87d,
    /// Identifier: "map-icon-rv-park"
    IFMapIconsRvPark                              = 0xe87e,
    /// Identifier: "map-icon-sailing"
    IFMapIconsSailing                             = 0xe87f,
    /// Identifier: "map-icon-school"
    IFMapIconsSchool                              = 0xe880,
    /// Identifier: "map-icon-scuba-diving"
    IFMapIconsScubaDiving                         = 0xe881,
    /// Identifier: "map-icon-search"
    IFMapIconsSearch                              = 0xe882,
    /// Identifier: "map-icon-shield"
    IFMapIconsShield                              = 0xe883,
    /// Identifier: "map-icon-shopping-mall"
    IFMapIconsShoppingMall                        = 0xe884,
    /// Identifier: "map-icon-sign-language"
    IFMapIconsSignLanguage                        = 0xe885,
    /// Identifier: "map-icon-skateboarding"
    IFMapIconsSkateboarding                       = 0xe886,
    /// Identifier: "map-icon-ski-jumping"
    IFMapIconsSkiJumping                          = 0xe887,
    /// Identifier: "map-icon-skiing"
    IFMapIconsSkiing                              = 0xe888,
    /// Identifier: "map-icon-sledding"
    IFMapIconsSledding                            = 0xe889,
    /// Identifier: "map-icon-snow-shoeing"
    IFMapIconsSnowShoeing                         = 0xe88a,
    /// Identifier: "map-icon-snow"
    IFMapIconsSnow                                = 0xe88b,
    /// Identifier: "map-icon-snowboarding"
    IFMapIconsSnowboarding                        = 0xe88c,
    /// Identifier: "map-icon-snowmobile"
    IFMapIconsSnowmobile                          = 0xe88d,
    /// Identifier: "map-icon-spa"
    IFMapIconsSpa                                 = 0xe88e,
    /// Identifier: "map-icon-square-pin"
    IFMapIconsSquarePin                           = 0xe88f,
    /// Identifier: "map-icon-square-rounded"
    IFMapIconsSquareRounded                       = 0xe890,
    /// Identifier: "map-icon-square"
    IFMapIconsSquare                              = 0xe891,
    /// Identifier: "map-icon-stadium"
    IFMapIconsStadium                             = 0xe892,
    /// Identifier: "map-icon-storage"
    IFMapIconsStorage                             = 0xe893,
    /// Identifier: "map-icon-store"
    IFMapIconsStore                               = 0xe894,
    /// Identifier: "map-icon-subway-station"
    IFMapIconsSubwayStation                       = 0xe895,
    /// Identifier: "map-icon-surfing"
    IFMapIconsSurfing                             = 0xe896,
    /// Identifier: "map-icon-swimming"
    IFMapIconsSwimming                            = 0xe897,
    /// Identifier: "map-icon-synagogue"
    IFMapIconsSynagogue                           = 0xe898,
    /// Identifier: "map-icon-taxi-stand"
    IFMapIconsTaxiStand                           = 0xe899,
    /// Identifier: "map-icon-tennis"
    IFMapIconsTennis                              = 0xe89a,
    /// Identifier: "map-icon-toilet"
    IFMapIconsToilet                              = 0xe89b,
    /// Identifier: "map-icon-trail-walking"
    IFMapIconsTrailWalking                        = 0xe89c,
    /// Identifier: "map-icon-train-station"
    IFMapIconsTrainStation                        = 0xe89d,
    /// Identifier: "map-icon-transit-station"
    IFMapIconsTransitStation                      = 0xe89e,
    /// Identifier: "map-icon-travel-agency"
    IFMapIconsTravelAgency                        = 0xe89f,
    /// Identifier: "map-icon-unisex"
    IFMapIconsUnisex                              = 0xe8a0,
    /// Identifier: "map-icon-university"
    IFMapIconsUniversity                          = 0xe8a1,
    /// Identifier: "map-icon-veterinary-care"
    IFMapIconsVeterinaryCare                      = 0xe8a2,
    /// Identifier: "map-icon-viewing"
    IFMapIconsViewing                             = 0xe8a3,
    /// Identifier: "map-icon-volume-control-telephone"
    IFMapIconsVolumeControlTelephone              = 0xe8a4,
    /// Identifier: "map-icon-walking"
    IFMapIconsWalking                             = 0xe8a5,
    /// Identifier: "map-icon-waterskiing"
    IFMapIconsWaterskiing                         = 0xe8a6,
    /// Identifier: "map-icon-whale-watching"
    IFMapIconsWhaleWatching                       = 0xe8a7,
    /// Identifier: "map-icon-wheelchair"
    IFMapIconsWheelchair                          = 0xe8a8,
    /// Identifier: "map-icon-wind-surfing"
    IFMapIconsWindSurfing                         = 0xe8a9,
    /// Identifier: "map-icon-zoo"
    IFMapIconsZoo                                 = 0xe8aa,
    /// Identifier: "map-icon-zoom-in-alt"
    IFMapIconsZoomInAlt                           = 0xe8ab,
    /// Identifier: "map-icon-zoom-in"
    IFMapIconsZoomIn                              = 0xe8ac,
    /// Identifier: "map-icon-zoom-out-alt"
    IFMapIconsZoomOutAlt                          = 0xe8ad,
    /// Identifier: "map-icon-zoom-out"
    IFMapIconsZoomOut                             = 0xe8ae,
};

/*!
 * MapIcons v3.0.0 http://map-icons.com
 */
@interface IFMapIcons : IFIcon
@end
