#import "IFStreamlineFree.h"

@implementation IFStreamlineFree

+ (NSURL *)fontFileURL
{
    return [[[NSBundle mainBundle] resourceURL] URLByAppendingPathComponent:@"StreamlineFree.ttf"];
}

+ (NSDictionary *)allIcons
{
    return @{
             @"sf-backpack":                             @"\ue900",
             @"sf-bomb":                                 @"\ue901",
             @"sf-book":                                 @"\ue902",
             @"sf-briefcase":                            @"\ue903",
             @"sf-bubble-chat":                          @"\ue904",
             @"sf-bubble-heart":                         @"\ue905",
             @"sf-camera-photo":                         @"\ue906",
             @"sf-camera-polaroid":                      @"\ue907",
             @"sf-camera-video":                         @"\ue908",
             @"sf-cassette-player":                      @"\ue909",
             @"sf-charlie-chaplin":                      @"\ue90a",
             @"sf-chef-hat":                             @"\ue90b",
             @"sf-clock":                                @"\ue90c",
             @"sf-coffee-machine":                       @"\ue90d",
             @"sf-cog":                                  @"\ue90e",
             @"sf-computer-imac":                        @"\ue90f",
             @"sf-computer-network":                     @"\ue910",
             @"sf-computer-pc":                          @"\ue911",
             @"sf-computer-screen-1":                    @"\ue912",
             @"sf-computer-screen-2":                    @"\ue913",
             @"sf-contact-book":                         @"\ue914",
             @"sf-content-download":                     @"\ue915",
             @"sf-cooking-pot":                          @"\ue916",
             @"sf-crop":                                 @"\ue917",
             @"sf-crown":                                @"\ue918",
             @"sf-designer-cup":                         @"\ue919",
             @"sf-diving-gear":                          @"\ue91a",
             @"sf-drink-cocktail":                       @"\ue91b",
             @"sf-drink-coffee":                         @"\ue91c",
             @"sf-e-mail":                               @"\ue91d",
             @"sf-envelope":                             @"\ue91e",
             @"sf-eyedropper":                           @"\ue91f",
             @"sf-fork-knife":                           @"\ue920",
             @"sf-forklift":                             @"\ue921",
             @"sf-fountain-pen-head-1":                  @"\ue922",
             @"sf-fountain-pen-head-2":                  @"\ue923",
             @"sf-gauge":                                @"\ue924",
             @"sf-globe":                                @"\ue925",
             @"sf-grid":                                 @"\ue926",
             @"sf-griller":                              @"\ue927",
             @"sf-handbag":                              @"\ue928",
             @"sf-headphone":                            @"\ue929",
             @"sf-heart":                                @"\ue92a",
             @"sf-home":                                 @"\ue92b",
             @"sf-hotdog":                               @"\ue92c",
             @"sf-icecream":                             @"\ue92d",
             @"sf-image":                                @"\ue92e",
             @"sf-iphone":                               @"\ue92f",
             @"sf-ipod":                                 @"\ue930",
             @"sf-layers-image":                         @"\ue931",
             @"sf-layers":                               @"\ue932",
             @"sf-link":                                 @"\ue933",
             @"sf-location-pin":                         @"\ue934",
             @"sf-location-user":                        @"\ue935",
             @"sf-lock-locked":                          @"\ue936",
             @"sf-lock-unlocked":                        @"\ue937",
             @"sf-magic-wand":                           @"\ue938",
             @"sf-magnet":                               @"\ue939",
             @"sf-microphone":                           @"\ue93a",
             @"sf-monocle":                              @"\ue93b",
             @"sf-mp3-player":                           @"\ue93c",
             @"sf-music-note":                           @"\ue93d",
             @"sf-notebook-1":                           @"\ue93e",
             @"sf-notebook-2":                           @"\ue93f",
             @"sf-paint-brush":                          @"\ue940",
             @"sf-paint-bucket":                         @"\ue941",
             @"sf-paint-palette":                        @"\ue942",
             @"sf-paint-roller":                         @"\ue943",
             @"sf-pen-fountain":                         @"\ue944",
             @"sf-pen-point-tip":                        @"\ue945",
             @"sf-pencil-ruler":                         @"\ue946",
             @"sf-picture-frame":                        @"\ue947",
             @"sf-quill-ink":                            @"\ue948",
             @"sf-refresh":                              @"\ue949",
             @"sf-remote-control-hand":                  @"\ue94a",
             @"sf-remote-control-screen":                @"\ue94b",
             @"sf-script":                               @"\ue94c",
             @"sf-server":                               @"\ue94d",
             @"sf-settings":                             @"\ue94e",
             @"sf-shield-cross":                         @"\ue94f",
             @"sf-shopping-cart-add":                    @"\ue950",
             @"sf-shopping-cart-remove":                 @"\ue951",
             @"sf-skull":                                @"\ue952",
             @"sf-smart-device":                         @"\ue953",
             @"sf-smiley":                               @"\ue954",
             @"sf-sneakers":                             @"\ue955",
             @"sf-sofa":                                 @"\ue956",
             @"sf-stamp":                                @"\ue957",
             @"sf-sub-woofer":                           @"\ue958",
             @"sf-syringe":                              @"\ue959",
             @"sf-target":                               @"\ue95a",
             @"sf-teapot":                               @"\ue95b",
             @"sf-trash-can":                            @"\ue95c",
             @"sf-umbrella":                             @"\ue95d",
             @"sf-user-chat":                            @"\ue95e",
             @"sf-user":                                 @"\ue95f",
             @"sf-vector":                               @"\ue960",
             @"sf-windows":                              @"\ue961",
             @"sf-wrenches":                             @"\ue962",
             @"sf-write":                                @"\ue963",
             };
}

@end
