#import <IconFontsKit/IFIcon.h>

/// Typicons icon types.
typedef NS_ENUM(IFIconType, IFTypiconsType) {
    /// Identifier: "typcn-adjust-brightness"
    IFTIAdjustBrightness                    = 0xe000,
    /// Identifier: "typcn-adjust-contrast"
    IFTIAdjustContrast                      = 0xe001,
    /// Identifier: "typcn-anchor-outline"
    IFTIAnchorOutline                       = 0xe002,
    /// Identifier: "typcn-anchor"
    IFTIAnchor                              = 0xe003,
    /// Identifier: "typcn-archive"
    IFTIArchive                             = 0xe004,
    /// Identifier: "typcn-arrow-back-outline"
    IFTIArrowBackOutline                    = 0xe005,
    /// Identifier: "typcn-arrow-back"
    IFTIArrowBack                           = 0xe006,
    /// Identifier: "typcn-arrow-down-outline"
    IFTIArrowDownOutline                    = 0xe007,
    /// Identifier: "typcn-arrow-down-thick"
    IFTIArrowDownThick                      = 0xe008,
    /// Identifier: "typcn-arrow-down"
    IFTIArrowDown                           = 0xe009,
    /// Identifier: "typcn-arrow-forward-outline"
    IFTIArrowForwardOutline                 = 0xe00a,
    /// Identifier: "typcn-arrow-forward"
    IFTIArrowForward                        = 0xe00b,
    /// Identifier: "typcn-arrow-left-outline"
    IFTIArrowLeftOutline                    = 0xe00c,
    /// Identifier: "typcn-arrow-left-thick"
    IFTIArrowLeftThick                      = 0xe00d,
    /// Identifier: "typcn-arrow-left"
    IFTIArrowLeft                           = 0xe00e,
    /// Identifier: "typcn-arrow-loop-outline"
    IFTIArrowLoopOutline                    = 0xe00f,
    /// Identifier: "typcn-arrow-loop"
    IFTIArrowLoop                           = 0xe010,
    /// Identifier: "typcn-arrow-maximise-outline"
    IFTIArrowMaximiseOutline                = 0xe011,
    /// Identifier: "typcn-arrow-maximise"
    IFTIArrowMaximise                       = 0xe012,
    /// Identifier: "typcn-arrow-minimise-outline"
    IFTIArrowMinimiseOutline                = 0xe013,
    /// Identifier: "typcn-arrow-minimise"
    IFTIArrowMinimise                       = 0xe014,
    /// Identifier: "typcn-arrow-move-outline"
    IFTIArrowMoveOutline                    = 0xe015,
    /// Identifier: "typcn-arrow-move"
    IFTIArrowMove                           = 0xe016,
    /// Identifier: "typcn-arrow-repeat-outline"
    IFTIArrowRepeatOutline                  = 0xe017,
    /// Identifier: "typcn-arrow-repeat"
    IFTIArrowRepeat                         = 0xe018,
    /// Identifier: "typcn-arrow-right-outline"
    IFTIArrowRightOutline                   = 0xe019,
    /// Identifier: "typcn-arrow-right-thick"
    IFTIArrowRightThick                     = 0xe01a,
    /// Identifier: "typcn-arrow-right"
    IFTIArrowRight                          = 0xe01b,
    /// Identifier: "typcn-arrow-shuffle"
    IFTIArrowShuffle                        = 0xe01c,
    /// Identifier: "typcn-arrow-sorted-down"
    IFTIArrowSortedDown                     = 0xe01d,
    /// Identifier: "typcn-arrow-sorted-up"
    IFTIArrowSortedUp                       = 0xe01e,
    /// Identifier: "typcn-arrow-sync-outline"
    IFTIArrowSyncOutline                    = 0xe01f,
    /// Identifier: "typcn-arrow-sync"
    IFTIArrowSync                           = 0xe020,
    /// Identifier: "typcn-arrow-unsorted"
    IFTIArrowUnsorted                       = 0xe021,
    /// Identifier: "typcn-arrow-up-outline"
    IFTIArrowUpOutline                      = 0xe022,
    /// Identifier: "typcn-arrow-up-thick"
    IFTIArrowUpThick                        = 0xe023,
    /// Identifier: "typcn-arrow-up"
    IFTIArrowUp                             = 0xe024,
    /// Identifier: "typcn-at"
    IFTIAt                                  = 0xe025,
    /// Identifier: "typcn-attachment-outline"
    IFTIAttachmentOutline                   = 0xe026,
    /// Identifier: "typcn-attachment"
    IFTIAttachment                          = 0xe027,
    /// Identifier: "typcn-backspace-outline"
    IFTIBackspaceOutline                    = 0xe028,
    /// Identifier: "typcn-backspace"
    IFTIBackspace                           = 0xe029,
    /// Identifier: "typcn-battery-charge"
    IFTIBatteryCharge                       = 0xe02a,
    /// Identifier: "typcn-battery-full"
    IFTIBatteryFull                         = 0xe02b,
    /// Identifier: "typcn-battery-high"
    IFTIBatteryHigh                         = 0xe02c,
    /// Identifier: "typcn-battery-low"
    IFTIBatteryLow                          = 0xe02d,
    /// Identifier: "typcn-battery-mid"
    IFTIBatteryMid                          = 0xe02e,
    /// Identifier: "typcn-beaker"
    IFTIBeaker                              = 0xe02f,
    /// Identifier: "typcn-beer"
    IFTIBeer                                = 0xe030,
    /// Identifier: "typcn-bell"
    IFTIBell                                = 0xe031,
    /// Identifier: "typcn-book"
    IFTIBook                                = 0xe032,
    /// Identifier: "typcn-bookmark"
    IFTIBookmark                            = 0xe033,
    /// Identifier: "typcn-briefcase"
    IFTIBriefcase                           = 0xe034,
    /// Identifier: "typcn-brush"
    IFTIBrush                               = 0xe035,
    /// Identifier: "typcn-business-card"
    IFTIBusinessCard                        = 0xe036,
    /// Identifier: "typcn-calculator"
    IFTICalculator                          = 0xe037,
    /// Identifier: "typcn-calendar-outline"
    IFTICalendarOutline                     = 0xe038,
    /// Identifier: "typcn-calendar"
    IFTICalendar                            = 0xe039,
    /// Identifier: "typcn-camera-outline"
    IFTICameraOutline                       = 0xe03a,
    /// Identifier: "typcn-camera"
    IFTICamera                              = 0xe03b,
    /// Identifier: "typcn-cancel-outline"
    IFTICancelOutline                       = 0xe03c,
    /// Identifier: "typcn-cancel"
    IFTICancel                              = 0xe03d,
    /// Identifier: "typcn-chart-area-outline"
    IFTIChartAreaOutline                    = 0xe03e,
    /// Identifier: "typcn-chart-area"
    IFTIChartArea                           = 0xe03f,
    /// Identifier: "typcn-chart-bar-outline"
    IFTIChartBarOutline                     = 0xe040,
    /// Identifier: "typcn-chart-bar"
    IFTIChartBar                            = 0xe041,
    /// Identifier: "typcn-chart-line-outline"
    IFTIChartLineOutline                    = 0xe042,
    /// Identifier: "typcn-chart-line"
    IFTIChartLine                           = 0xe043,
    /// Identifier: "typcn-chart-pie-outline"
    IFTIChartPieOutline                     = 0xe044,
    /// Identifier: "typcn-chart-pie"
    IFTIChartPie                            = 0xe045,
    /// Identifier: "typcn-chevron-left-outline"
    IFTIChevronLeftOutline                  = 0xe046,
    /// Identifier: "typcn-chevron-left"
    IFTIChevronLeft                         = 0xe047,
    /// Identifier: "typcn-chevron-right-outline"
    IFTIChevronRightOutline                 = 0xe048,
    /// Identifier: "typcn-chevron-right"
    IFTIChevronRight                        = 0xe049,
    /// Identifier: "typcn-clipboard"
    IFTIClipboard                           = 0xe04a,
    /// Identifier: "typcn-cloud-storage"
    IFTICloudStorage                        = 0xe04b,
    /// Identifier: "typcn-cloud-storage-outline"
    IFTICloudStorageOutline                 = 0xe054,
    /// Identifier: "typcn-code-outline"
    IFTICodeOutline                         = 0xe04c,
    /// Identifier: "typcn-code"
    IFTICode                                = 0xe04d,
    /// Identifier: "typcn-coffee"
    IFTICoffee                              = 0xe04e,
    /// Identifier: "typcn-cog-outline"
    IFTICogOutline                          = 0xe04f,
    /// Identifier: "typcn-cog"
    IFTICog                                 = 0xe050,
    /// Identifier: "typcn-compass"
    IFTICompass                             = 0xe051,
    /// Identifier: "typcn-contacts"
    IFTIContacts                            = 0xe052,
    /// Identifier: "typcn-credit-card"
    IFTICreditCard                          = 0xe053,
    /// Identifier: "typcn-css3"
    IFTICss3                                = 0xe055,
    /// Identifier: "typcn-database"
    IFTIDatabase                            = 0xe056,
    /// Identifier: "typcn-delete-outline"
    IFTIDeleteOutline                       = 0xe057,
    /// Identifier: "typcn-delete"
    IFTIDelete                              = 0xe058,
    /// Identifier: "typcn-device-desktop"
    IFTIDeviceDesktop                       = 0xe059,
    /// Identifier: "typcn-device-laptop"
    IFTIDeviceLaptop                        = 0xe05a,
    /// Identifier: "typcn-device-phone"
    IFTIDevicePhone                         = 0xe05b,
    /// Identifier: "typcn-device-tablet"
    IFTIDeviceTablet                        = 0xe05c,
    /// Identifier: "typcn-directions"
    IFTIDirections                          = 0xe05d,
    /// Identifier: "typcn-divide-outline"
    IFTIDivideOutline                       = 0xe05e,
    /// Identifier: "typcn-divide"
    IFTIDivide                              = 0xe05f,
    /// Identifier: "typcn-document-add"
    IFTIDocumentAdd                         = 0xe060,
    /// Identifier: "typcn-document-delete"
    IFTIDocumentDelete                      = 0xe061,
    /// Identifier: "typcn-document-text"
    IFTIDocumentText                        = 0xe062,
    /// Identifier: "typcn-document"
    IFTIDocument                            = 0xe063,
    /// Identifier: "typcn-download-outline"
    IFTIDownloadOutline                     = 0xe064,
    /// Identifier: "typcn-download"
    IFTIDownload                            = 0xe065,
    /// Identifier: "typcn-dropbox"
    IFTIDropbox                             = 0xe066,
    /// Identifier: "typcn-edit"
    IFTIEdit                                = 0xe067,
    /// Identifier: "typcn-eject-outline"
    IFTIEjectOutline                        = 0xe068,
    /// Identifier: "typcn-eject"
    IFTIEject                               = 0xe069,
    /// Identifier: "typcn-equals-outline"
    IFTIEqualsOutline                       = 0xe06a,
    /// Identifier: "typcn-equals"
    IFTIEquals                              = 0xe06b,
    /// Identifier: "typcn-export-outline"
    IFTIExportOutline                       = 0xe06c,
    /// Identifier: "typcn-export"
    IFTIExport                              = 0xe06d,
    /// Identifier: "typcn-eye-outline"
    IFTIEyeOutline                          = 0xe06e,
    /// Identifier: "typcn-eye"
    IFTIEye                                 = 0xe06f,
    /// Identifier: "typcn-feather"
    IFTIFeather                             = 0xe070,
    /// Identifier: "typcn-film"
    IFTIFilm                                = 0xe071,
    /// Identifier: "typcn-filter"
    IFTIFilter                              = 0xe072,
    /// Identifier: "typcn-flag-outline"
    IFTIFlagOutline                         = 0xe073,
    /// Identifier: "typcn-flag"
    IFTIFlag                                = 0xe074,
    /// Identifier: "typcn-flash-outline"
    IFTIFlashOutline                        = 0xe075,
    /// Identifier: "typcn-flash"
    IFTIFlash                               = 0xe076,
    /// Identifier: "typcn-flow-children"
    IFTIFlowChildren                        = 0xe077,
    /// Identifier: "typcn-flow-merge"
    IFTIFlowMerge                           = 0xe078,
    /// Identifier: "typcn-flow-parallel"
    IFTIFlowParallel                        = 0xe079,
    /// Identifier: "typcn-flow-switch"
    IFTIFlowSwitch                          = 0xe07a,
    /// Identifier: "typcn-folder-add"
    IFTIFolderAdd                           = 0xe07b,
    /// Identifier: "typcn-folder-delete"
    IFTIFolderDelete                        = 0xe07c,
    /// Identifier: "typcn-folder-open"
    IFTIFolderOpen                          = 0xe07d,
    /// Identifier: "typcn-folder"
    IFTIFolder                              = 0xe07e,
    /// Identifier: "typcn-gift"
    IFTIGift                                = 0xe07f,
    /// Identifier: "typcn-globe-outline"
    IFTIGlobeOutline                        = 0xe080,
    /// Identifier: "typcn-globe"
    IFTIGlobe                               = 0xe081,
    /// Identifier: "typcn-group-outline"
    IFTIGroupOutline                        = 0xe082,
    /// Identifier: "typcn-group"
    IFTIGroup                               = 0xe083,
    /// Identifier: "typcn-headphones"
    IFTIHeadphones                          = 0xe084,
    /// Identifier: "typcn-heart-full-outline"
    IFTIHeartFullOutline                    = 0xe085,
    /// Identifier: "typcn-heart-half-outline"
    IFTIHeartHalfOutline                    = 0xe086,
    /// Identifier: "typcn-heart-outline"
    IFTIHeartOutline                        = 0xe087,
    /// Identifier: "typcn-heart"
    IFTIHeart                               = 0xe088,
    /// Identifier: "typcn-home-outline"
    IFTIHomeOutline                         = 0xe089,
    /// Identifier: "typcn-home"
    IFTIHome                                = 0xe08a,
    /// Identifier: "typcn-html5"
    IFTIHtml5                               = 0xe08b,
    /// Identifier: "typcn-image-outline"
    IFTIImageOutline                        = 0xe08c,
    /// Identifier: "typcn-image"
    IFTIImage                               = 0xe08d,
    /// Identifier: "typcn-infinity-outline"
    IFTIInfinityOutline                     = 0xe08e,
    /// Identifier: "typcn-infinity"
    IFTIInfinity                            = 0xe08f,
    /// Identifier: "typcn-info-large-outline"
    IFTIInfoLargeOutline                    = 0xe090,
    /// Identifier: "typcn-info-large"
    IFTIInfoLarge                           = 0xe091,
    /// Identifier: "typcn-info-outline"
    IFTIInfoOutline                         = 0xe092,
    /// Identifier: "typcn-info"
    IFTIInfo                                = 0xe093,
    /// Identifier: "typcn-input-checked-outline"
    IFTIInputCheckedOutline                 = 0xe094,
    /// Identifier: "typcn-input-checked"
    IFTIInputChecked                        = 0xe095,
    /// Identifier: "typcn-key-outline"
    IFTIKeyOutline                          = 0xe096,
    /// Identifier: "typcn-key"
    IFTIKey                                 = 0xe097,
    /// Identifier: "typcn-keyboard"
    IFTIKeyboard                            = 0xe098,
    /// Identifier: "typcn-leaf"
    IFTILeaf                                = 0xe099,
    /// Identifier: "typcn-lightbulb"
    IFTILightbulb                           = 0xe09a,
    /// Identifier: "typcn-link-outline"
    IFTILinkOutline                         = 0xe09b,
    /// Identifier: "typcn-link"
    IFTILink                                = 0xe09c,
    /// Identifier: "typcn-location-arrow-outline"
    IFTILocationArrowOutline                = 0xe09d,
    /// Identifier: "typcn-location-arrow"
    IFTILocationArrow                       = 0xe09e,
    /// Identifier: "typcn-location-outline"
    IFTILocationOutline                     = 0xe09f,
    /// Identifier: "typcn-location"
    IFTILocation                            = 0xe0a0,
    /// Identifier: "typcn-lock-closed-outline"
    IFTILockClosedOutline                   = 0xe0a1,
    /// Identifier: "typcn-lock-closed"
    IFTILockClosed                          = 0xe0a2,
    /// Identifier: "typcn-lock-open-outline"
    IFTILockOpenOutline                     = 0xe0a3,
    /// Identifier: "typcn-lock-open"
    IFTILockOpen                            = 0xe0a4,
    /// Identifier: "typcn-mail"
    IFTIMail                                = 0xe0a5,
    /// Identifier: "typcn-map"
    IFTIMap                                 = 0xe0a6,
    /// Identifier: "typcn-media-eject-outline"
    IFTIMediaEjectOutline                   = 0xe0a7,
    /// Identifier: "typcn-media-eject"
    IFTIMediaEject                          = 0xe0a8,
    /// Identifier: "typcn-media-fast-forward-outline"
    IFTIMediaFastForwardOutline             = 0xe0a9,
    /// Identifier: "typcn-media-fast-forward"
    IFTIMediaFastForward                    = 0xe0aa,
    /// Identifier: "typcn-media-pause-outline"
    IFTIMediaPauseOutline                   = 0xe0ab,
    /// Identifier: "typcn-media-pause"
    IFTIMediaPause                          = 0xe0ac,
    /// Identifier: "typcn-media-play-outline"
    IFTIMediaPlayOutline                    = 0xe0ad,
    /// Identifier: "typcn-media-play-reverse-outline"
    IFTIMediaPlayReverseOutline             = 0xe0ae,
    /// Identifier: "typcn-media-play-reverse"
    IFTIMediaPlayReverse                    = 0xe0af,
    /// Identifier: "typcn-media-play"
    IFTIMediaPlay                           = 0xe0b0,
    /// Identifier: "typcn-media-record-outline"
    IFTIMediaRecordOutline                  = 0xe0b1,
    /// Identifier: "typcn-media-record"
    IFTIMediaRecord                         = 0xe0b2,
    /// Identifier: "typcn-media-rewind-outline"
    IFTIMediaRewindOutline                  = 0xe0b3,
    /// Identifier: "typcn-media-rewind"
    IFTIMediaRewind                         = 0xe0b4,
    /// Identifier: "typcn-media-stop-outline"
    IFTIMediaStopOutline                    = 0xe0b5,
    /// Identifier: "typcn-media-stop"
    IFTIMediaStop                           = 0xe0b6,
    /// Identifier: "typcn-message-typing"
    IFTIMessageTyping                       = 0xe0b7,
    /// Identifier: "typcn-message"
    IFTIMessage                             = 0xe0b8,
    /// Identifier: "typcn-messages"
    IFTIMessages                            = 0xe0b9,
    /// Identifier: "typcn-microphone-outline"
    IFTIMicrophoneOutline                   = 0xe0ba,
    /// Identifier: "typcn-microphone"
    IFTIMicrophone                          = 0xe0bb,
    /// Identifier: "typcn-minus-outline"
    IFTIMinusOutline                        = 0xe0bc,
    /// Identifier: "typcn-minus"
    IFTIMinus                               = 0xe0bd,
    /// Identifier: "typcn-mortar-board"
    IFTIMortarBoard                         = 0xe0be,
    /// Identifier: "typcn-news"
    IFTINews                                = 0xe0bf,
    /// Identifier: "typcn-notes-outline"
    IFTINotesOutline                        = 0xe0c0,
    /// Identifier: "typcn-notes"
    IFTINotes                               = 0xe0c1,
    /// Identifier: "typcn-pen"
    IFTIPen                                 = 0xe0c2,
    /// Identifier: "typcn-pencil"
    IFTIPencil                              = 0xe0c3,
    /// Identifier: "typcn-phone-outline"
    IFTIPhoneOutline                        = 0xe0c4,
    /// Identifier: "typcn-phone"
    IFTIPhone                               = 0xe0c5,
    /// Identifier: "typcn-pi-outline"
    IFTIPiOutline                           = 0xe0c6,
    /// Identifier: "typcn-pi"
    IFTIPi                                  = 0xe0c7,
    /// Identifier: "typcn-pin-outline"
    IFTIPinOutline                          = 0xe0c8,
    /// Identifier: "typcn-pin"
    IFTIPin                                 = 0xe0c9,
    /// Identifier: "typcn-pipette"
    IFTIPipette                             = 0xe0ca,
    /// Identifier: "typcn-plane-outline"
    IFTIPlaneOutline                        = 0xe0cb,
    /// Identifier: "typcn-plane"
    IFTIPlane                               = 0xe0cc,
    /// Identifier: "typcn-plug"
    IFTIPlug                                = 0xe0cd,
    /// Identifier: "typcn-plus-outline"
    IFTIPlusOutline                         = 0xe0ce,
    /// Identifier: "typcn-plus"
    IFTIPlus                                = 0xe0cf,
    /// Identifier: "typcn-point-of-interest-outline"
    IFTIPointOfInterestOutline              = 0xe0d0,
    /// Identifier: "typcn-point-of-interest"
    IFTIPointOfInterest                     = 0xe0d1,
    /// Identifier: "typcn-power-outline"
    IFTIPowerOutline                        = 0xe0d2,
    /// Identifier: "typcn-power"
    IFTIPower                               = 0xe0d3,
    /// Identifier: "typcn-printer"
    IFTIPrinter                             = 0xe0d4,
    /// Identifier: "typcn-puzzle-outline"
    IFTIPuzzleOutline                       = 0xe0d5,
    /// Identifier: "typcn-puzzle"
    IFTIPuzzle                              = 0xe0d6,
    /// Identifier: "typcn-radar-outline"
    IFTIRadarOutline                        = 0xe0d7,
    /// Identifier: "typcn-radar"
    IFTIRadar                               = 0xe0d8,
    /// Identifier: "typcn-refresh-outline"
    IFTIRefreshOutline                      = 0xe0d9,
    /// Identifier: "typcn-refresh"
    IFTIRefresh                             = 0xe0da,
    /// Identifier: "typcn-rss-outline"
    IFTIRssOutline                          = 0xe0db,
    /// Identifier: "typcn-rss"
    IFTIRss                                 = 0xe0dc,
    /// Identifier: "typcn-scissors-outline"
    IFTIScissorsOutline                     = 0xe0dd,
    /// Identifier: "typcn-scissors"
    IFTIScissors                            = 0xe0de,
    /// Identifier: "typcn-shopping-bag"
    IFTIShoppingBag                         = 0xe0df,
    /// Identifier: "typcn-shopping-cart"
    IFTIShoppingCart                        = 0xe0e0,
    /// Identifier: "typcn-social-at-circular"
    IFTISocialAtCircular                    = 0xe0e1,
    /// Identifier: "typcn-social-dribbble-circular"
    IFTISocialDribbbleCircular              = 0xe0e2,
    /// Identifier: "typcn-social-dribbble"
    IFTISocialDribbble                      = 0xe0e3,
    /// Identifier: "typcn-social-facebook-circular"
    IFTISocialFacebookCircular              = 0xe0e4,
    /// Identifier: "typcn-social-facebook"
    IFTISocialFacebook                      = 0xe0e5,
    /// Identifier: "typcn-social-flickr-circular"
    IFTISocialFlickrCircular                = 0xe0e6,
    /// Identifier: "typcn-social-flickr"
    IFTISocialFlickr                        = 0xe0e7,
    /// Identifier: "typcn-social-github-circular"
    IFTISocialGithubCircular                = 0xe0e8,
    /// Identifier: "typcn-social-github"
    IFTISocialGithub                        = 0xe0e9,
    /// Identifier: "typcn-social-google-plus-circular"
    IFTISocialGooglePlusCircular            = 0xe0ea,
    /// Identifier: "typcn-social-google-plus"
    IFTISocialGooglePlus                    = 0xe0eb,
    /// Identifier: "typcn-social-instagram-circular"
    IFTISocialInstagramCircular             = 0xe0ec,
    /// Identifier: "typcn-social-instagram"
    IFTISocialInstagram                     = 0xe0ed,
    /// Identifier: "typcn-social-last-fm-circular"
    IFTISocialLastFmCircular                = 0xe0ee,
    /// Identifier: "typcn-social-last-fm"
    IFTISocialLastFm                        = 0xe0ef,
    /// Identifier: "typcn-social-linkedin-circular"
    IFTISocialLinkedinCircular              = 0xe0f0,
    /// Identifier: "typcn-social-linkedin"
    IFTISocialLinkedin                      = 0xe0f1,
    /// Identifier: "typcn-social-pinterest-circular"
    IFTISocialPinterestCircular             = 0xe0f2,
    /// Identifier: "typcn-social-pinterest"
    IFTISocialPinterest                     = 0xe0f3,
    /// Identifier: "typcn-social-skype-outline"
    IFTISocialSkypeOutline                  = 0xe0f4,
    /// Identifier: "typcn-social-skype"
    IFTISocialSkype                         = 0xe0f5,
    /// Identifier: "typcn-social-tumbler-circular"
    IFTISocialTumblerCircular               = 0xe0f6,
    /// Identifier: "typcn-social-tumbler"
    IFTISocialTumbler                       = 0xe0f7,
    /// Identifier: "typcn-social-twitter-circular"
    IFTISocialTwitterCircular               = 0xe0f8,
    /// Identifier: "typcn-social-twitter"
    IFTISocialTwitter                       = 0xe0f9,
    /// Identifier: "typcn-social-vimeo-circular"
    IFTISocialVimeoCircular                 = 0xe0fa,
    /// Identifier: "typcn-social-vimeo"
    IFTISocialVimeo                         = 0xe0fb,
    /// Identifier: "typcn-social-youtube-circular"
    IFTISocialYoutubeCircular               = 0xe0fc,
    /// Identifier: "typcn-social-youtube"
    IFTISocialYoutube                       = 0xe0fd,
    /// Identifier: "typcn-sort-alphabetically-outline"
    IFTISortAlphabeticallyOutline           = 0xe0fe,
    /// Identifier: "typcn-sort-alphabetically"
    IFTISortAlphabetically                  = 0xe0ff,
    /// Identifier: "typcn-sort-numerically-outline"
    IFTISortNumericallyOutline              = 0xe100,
    /// Identifier: "typcn-sort-numerically"
    IFTISortNumerically                     = 0xe101,
    /// Identifier: "typcn-spanner-outline"
    IFTISpannerOutline                      = 0xe102,
    /// Identifier: "typcn-spanner"
    IFTISpanner                             = 0xe103,
    /// Identifier: "typcn-spiral"
    IFTISpiral                              = 0xe104,
    /// Identifier: "typcn-star-full-outline"
    IFTIStarFullOutline                     = 0xe105,
    /// Identifier: "typcn-star-half-outline"
    IFTIStarHalfOutline                     = 0xe106,
    /// Identifier: "typcn-star-half"
    IFTIStarHalf                            = 0xe107,
    /// Identifier: "typcn-star-outline"
    IFTIStarOutline                         = 0xe108,
    /// Identifier: "typcn-star"
    IFTIStar                                = 0xe109,
    /// Identifier: "typcn-starburst-outline"
    IFTIStarburstOutline                    = 0xe10a,
    /// Identifier: "typcn-starburst"
    IFTIStarburst                           = 0xe10b,
    /// Identifier: "typcn-stopwatch"
    IFTIStopwatch                           = 0xe10c,
    /// Identifier: "typcn-support"
    IFTISupport                             = 0xe10d,
    /// Identifier: "typcn-tabs-outline"
    IFTITabsOutline                         = 0xe10e,
    /// Identifier: "typcn-tag"
    IFTITag                                 = 0xe10f,
    /// Identifier: "typcn-tags"
    IFTITags                                = 0xe110,
    /// Identifier: "typcn-th-large-outline"
    IFTIThLargeOutline                      = 0xe111,
    /// Identifier: "typcn-th-large"
    IFTIThLarge                             = 0xe112,
    /// Identifier: "typcn-th-list-outline"
    IFTIThListOutline                       = 0xe113,
    /// Identifier: "typcn-th-list"
    IFTIThList                              = 0xe114,
    /// Identifier: "typcn-th-menu-outline"
    IFTIThMenuOutline                       = 0xe115,
    /// Identifier: "typcn-th-menu"
    IFTIThMenu                              = 0xe116,
    /// Identifier: "typcn-th-small-outline"
    IFTIThSmallOutline                      = 0xe117,
    /// Identifier: "typcn-th-small"
    IFTIThSmall                             = 0xe118,
    /// Identifier: "typcn-thermometer"
    IFTIThermometer                         = 0xe119,
    /// Identifier: "typcn-thumbs-down"
    IFTIThumbsDown                          = 0xe11a,
    /// Identifier: "typcn-thumbs-ok"
    IFTIThumbsOk                            = 0xe11b,
    /// Identifier: "typcn-thumbs-up"
    IFTIThumbsUp                            = 0xe11c,
    /// Identifier: "typcn-tick-outline"
    IFTITickOutline                         = 0xe11d,
    /// Identifier: "typcn-tick"
    IFTITick                                = 0xe11e,
    /// Identifier: "typcn-ticket"
    IFTITicket                              = 0xe11f,
    /// Identifier: "typcn-time"
    IFTITime                                = 0xe120,
    /// Identifier: "typcn-times-outline"
    IFTITimesOutline                        = 0xe121,
    /// Identifier: "typcn-times"
    IFTITimes                               = 0xe122,
    /// Identifier: "typcn-trash"
    IFTITrash                               = 0xe123,
    /// Identifier: "typcn-tree"
    IFTITree                                = 0xe124,
    /// Identifier: "typcn-upload-outline"
    IFTIUploadOutline                       = 0xe125,
    /// Identifier: "typcn-upload"
    IFTIUpload                              = 0xe126,
    /// Identifier: "typcn-user-add-outline"
    IFTIUserAddOutline                      = 0xe127,
    /// Identifier: "typcn-user-add"
    IFTIUserAdd                             = 0xe128,
    /// Identifier: "typcn-user-delete-outline"
    IFTIUserDeleteOutline                   = 0xe129,
    /// Identifier: "typcn-user-delete"
    IFTIUserDelete                          = 0xe12a,
    /// Identifier: "typcn-user-outline"
    IFTIUserOutline                         = 0xe12b,
    /// Identifier: "typcn-user"
    IFTIUser                                = 0xe12c,
    /// Identifier: "typcn-vendor-android"
    IFTIVendorAndroid                       = 0xe12d,
    /// Identifier: "typcn-vendor-apple"
    IFTIVendorApple                         = 0xe12e,
    /// Identifier: "typcn-vendor-microsoft"
    IFTIVendorMicrosoft                     = 0xe12f,
    /// Identifier: "typcn-video-outline"
    IFTIVideoOutline                        = 0xe130,
    /// Identifier: "typcn-video"
    IFTIVideo                               = 0xe131,
    /// Identifier: "typcn-volume-down"
    IFTIVolumeDown                          = 0xe132,
    /// Identifier: "typcn-volume-mute"
    IFTIVolumeMute                          = 0xe133,
    /// Identifier: "typcn-volume-up"
    IFTIVolumeUp                            = 0xe134,
    /// Identifier: "typcn-volume"
    IFTIVolume                              = 0xe135,
    /// Identifier: "typcn-warning-outline"
    IFTIWarningOutline                      = 0xe136,
    /// Identifier: "typcn-warning"
    IFTIWarning                             = 0xe137,
    /// Identifier: "typcn-watch"
    IFTIWatch                               = 0xe138,
    /// Identifier: "typcn-waves-outline"
    IFTIWavesOutline                        = 0xe139,
    /// Identifier: "typcn-waves"
    IFTIWaves                               = 0xe13a,
    /// Identifier: "typcn-weather-cloudy"
    IFTIWeatherCloudy                       = 0xe13b,
    /// Identifier: "typcn-weather-downpour"
    IFTIWeatherDownpour                     = 0xe13c,
    /// Identifier: "typcn-weather-night"
    IFTIWeatherNight                        = 0xe13d,
    /// Identifier: "typcn-weather-partly-sunny"
    IFTIWeatherPartlySunny                  = 0xe13e,
    /// Identifier: "typcn-weather-shower"
    IFTIWeatherShower                       = 0xe13f,
    /// Identifier: "typcn-weather-snow"
    IFTIWeatherSnow                         = 0xe140,
    /// Identifier: "typcn-weather-stormy"
    IFTIWeatherStormy                       = 0xe141,
    /// Identifier: "typcn-weather-sunny"
    IFTIWeatherSunny                        = 0xe142,
    /// Identifier: "typcn-weather-windy-cloudy"
    IFTIWeatherWindyCloudy                  = 0xe143,
    /// Identifier: "typcn-weather-windy"
    IFTIWeatherWindy                        = 0xe144,
    /// Identifier: "typcn-wi-fi-outline"
    IFTIWiFiOutline                         = 0xe145,
    /// Identifier: "typcn-wi-fi"
    IFTIWiFi                                = 0xe146,
    /// Identifier: "typcn-wine"
    IFTIWine                                = 0xe147,
    /// Identifier: "typcn-world-outline"
    IFTIWorldOutline                        = 0xe148,
    /// Identifier: "typcn-world"
    IFTIWorld                               = 0xe149,
    /// Identifier: "typcn-zoom-in-outline"
    IFTIZoomInOutline                       = 0xe14a,
    /// Identifier: "typcn-zoom-in"
    IFTIZoomIn                              = 0xe14b,
    /// Identifier: "typcn-zoom-out-outline"
    IFTIZoomOutOutline                      = 0xe14c,
    /// Identifier: "typcn-zoom-out"
    IFTIZoomOut                             = 0xe14d,
    /// Identifier: "typcn-zoom-outline"
    IFTIZoomOutline                         = 0xe14e,
    /// Identifier: "typcn-zoom"
    IFTIZoom                                = 0xe14f,
};

/*!
 * Typicons v2.0.7 http://www.typicons.com
 */
@interface IFTypicons : IFIcon
@end
