//
// ZocialButtons v1.2.0 http://zocial.smcllns.com
// Generated on 2016-02-22
//

#import <IconFontsKit/IFIcon.h>

typedef NS_ENUM(IFIconType, IFZocialButtonsType) {
    IFZBAcrobat                             = 0xf100,
    IFZBAmazon                              = 0xf101,
    IFZBAndroid                             = 0xf102,
    IFZBAngellist                           = 0xf103,
    IFZBAol                                 = 0xf104,
    IFZBAppnet                              = 0xf105,
    IFZBAppstore                            = 0xf106,
    IFZBBitbucket                           = 0xf107,
    IFZBBitcoin                             = 0xf108,
    IFZBBlogger                             = 0xf109,
    IFZBBuffer                              = 0xf10a,
    IFZBCal                                 = 0xf10b,
    IFZBCall                                = 0xf10c,
    IFZBCart                                = 0xf10d,
    IFZBChrome                              = 0xf10e,
    IFZBCloudapp                            = 0xf10f,
    IFZBCreativecommons                     = 0xf110,
    IFZBDelicious                           = 0xf111,
    IFZBDigg                                = 0xf112,
    IFZBDisqus                              = 0xf113,
    IFZBDribbble                            = 0xf114,
    IFZBDropbox                             = 0xf115,
    IFZBDrupal                              = 0xf116,
    IFZBDwolla                              = 0xf118,
    IFZBEmail                               = 0xf119,
    IFZBEventasaurus                        = 0xf11a,
    IFZBEventbrite                          = 0xf11b,
    IFZBEventful                            = 0xf11c,
    IFZBEvernote                            = 0xf11d,
    IFZBFacebook                            = 0xf11e,
    IFZBFivehundredpx                       = 0xf11f,
    IFZBFlattr                              = 0xf120,
    IFZBFlickr                              = 0xf121,
    IFZBForrst                              = 0xf122,
    IFZBFoursquare                          = 0xf123,
    IFZBGithub                              = 0xf124,
    IFZBGmail                               = 0xf125,
    IFZBGoogle                              = 0xf126,
    IFZBGoogleplay                          = 0xf127,
    IFZBGoogleplus                          = 0xf128,
    IFZBGowalla                             = 0xf129,
    IFZBGrooveshark                         = 0xf12a,
    IFZBGuest                               = 0xf12b,
    IFZBHtml5                               = 0xf12c,
    IFZBIe                                  = 0xf12d,
    IFZBInstagram                           = 0xf12e,
    IFZBInstapaper                          = 0xf12f,
    IFZBIntensedebate                       = 0xf130,
    IFZBItunes                              = 0xf131,
    IFZBJoinme                              = 0xf165,
    IFZBKlout                               = 0xf132,
    IFZBLanyrd                              = 0xf133,
    IFZBLastfm                              = 0xf134,
    IFZBLego                                = 0xf135,
    IFZBLinkedin                            = 0xf136,
    IFZBLkdto                               = 0xf137,
    IFZBLogmein                             = 0xf138,
    IFZBMacstore                            = 0xf139,
    IFZBMeetup                              = 0xf13a,
    IFZBMyspace                             = 0xf13b,
    IFZBNinetyninedesigns                   = 0xf13c,
    IFZBOpenid                              = 0xf13d,
    IFZBOpentable                           = 0xf13e,
    IFZBPaypal                              = 0xf13f,
    IFZBPersona                             = 0xf164,
    IFZBPinboard                            = 0xf140,
    IFZBPinterest                           = 0xf141,
    IFZBPlancast                            = 0xf142,
    IFZBPlurk                               = 0xf143,
    IFZBPocket                              = 0xf144,
    IFZBPodcast                             = 0xf145,
    IFZBPosterous                           = 0xf146,
    IFZBPrint                               = 0xf147,
    IFZBQuora                               = 0xf148,
    IFZBReddit                              = 0xf149,
    IFZBRss                                 = 0xf14a,
    IFZBScribd                              = 0xf14b,
    IFZBSkype                               = 0xf14c,
    IFZBSmashing                            = 0xf14d,
    IFZBSongkick                            = 0xf14e,
    IFZBSoundcloud                          = 0xf14f,
    IFZBSpotify                             = 0xf150,
    IFZBStackoverflow                       = 0xf151,
    IFZBStatusnet                           = 0xf152,
    IFZBSteam                               = 0xf153,
    IFZBStripe                              = 0xf154,
    IFZBStumbleupon                         = 0xf155,
    IFZBTumblr                              = 0xf156,
    IFZBTwitch                              = 0xf166,
    IFZBTwitter                             = 0xf157,
    IFZBViadeo                              = 0xf158,
    IFZBVimeo                               = 0xf159,
    IFZBVk                                  = 0xf15a,
    IFZBWeibo                               = 0xf15b,
    IFZBWikipedia                           = 0xf15c,
    IFZBWindows                             = 0xf15d,
    IFZBWordpress                           = 0xf15e,
    IFZBXing                                = 0xf15f,
    IFZBYahoo                               = 0xf160,
    IFZBYcombinator                         = 0xf161,
    IFZBYelp                                = 0xf162,
    IFZBYoutube                             = 0xf163,
};

@interface IFZocialButtons : IFIcon
@end
