platform :ios, '7.0'
workspace '../IconFontsKit.xcworkspace'

target 'IconFontsKitExample' do
    pod "IconFontsKit", :path => "../IconFontsKit.podspec"
    pod "JTSImageViewController"
    pod "CHTCollectionViewWaterfallLayout"
end
