#import "IFMFGLabsIconset.h"

@implementation IFMFGLabsIconset

+ (NSURL *)fontFileURL
{
    return [[[NSBundle mainBundle] resourceURL] URLByAppendingPathComponent:@"mfglabsiconset-webfont.ttf"];
}

+ (NSString *)fontName
{
    return @"MFG Labs Iconset";
}

+ (NSDictionary *)allIcons
{
    return @{
             @"icon-cloud":                              @"\u2601",
             @"icon-at":                                 [NSString stringWithFormat:@"%C", 0x0040],
             @"icon-plus":                               [NSString stringWithFormat:@"%C", 0x002B],
             @"icon-minus":                              @"\u2212",
             @"icon-arrow_up":                           @"\u2191",
             @"icon-arrow_down":                         @"\u2193",
             @"icon-arrow_right":                        @"\u2192",
             @"icon-arrow_left":                         @"\u2190",
             @"icon-chevron_down":                       @"\uf004",
             @"icon-chevron_up":                         @"\uf005",
             @"icon-chevron_right":                      @"\uf006",
             @"icon-chevron_left":                       @"\uf007",
             @"icon-reorder":                            @"\uf008",
             @"icon-list":                               @"\uf009",
             @"icon-reorder_square":                     @"\uf00a",
             @"icon-reorder_square_line":                @"\uf00b",
             @"icon-coverflow":                          @"\uf00c",
             @"icon-coverflow_line":                     @"\uf00d",
             @"icon-pause":                              @"\uf00e",
             @"icon-play":                               @"\uf00f",
             @"icon-step_forward":                       @"\uf010",
             @"icon-step_backward":                      @"\uf011",
             @"icon-fast_forward":                       @"\uf012",
             @"icon-fast_backward":                      @"\uf013",
             @"icon-cloud_upload":                       @"\uf014",
             @"icon-cloud_download":                     @"\uf015",
             @"icon-data_science":                       @"\uf016",
             @"icon-data_science_black":                 @"\uf017",
             @"icon-globe":                              @"\uf018",
             @"icon-globe_black":                        @"\uf019",
             @"icon-math_ico":                           @"\uf01a",
             @"icon-math":                               @"\uf01b",
             @"icon-math_black":                         @"\uf01c",
             @"icon-paperplane_ico":                     @"\uf01d",
             @"icon-paperplane":                         @"\uf01e",
             @"icon-paperplane_black":                   @"\uf01f",
             @"icon-color_balance":                      @"\uf020",
             @"icon-star":                               @"\u2605",
             @"icon-star_half":                          @"\uf022",
             @"icon-star_empty":                         @"\u2606",
             @"icon-star_half_empty":                    @"\uf024",
             @"icon-reload":                             @"\uf025",
             @"icon-heart":                              @"\u2665",
             @"icon-heart_broken":                       @"\uf028",
             @"icon-hashtag":                            @"\uf029",
             @"icon-reply":                              @"\uf02a",
             @"icon-retweet":                            @"\uf02b",
             @"icon-signin":                             @"\uf02c",
             @"icon-signout":                            @"\uf02d",
             @"icon-download":                           @"\uf02e",
             @"icon-upload":                             @"\uf02f",
             @"icon-placepin":                           @"\uf031",
             @"icon-display_screen":                     @"\uf032",
             @"icon-tablet":                             @"\uf033",
             @"icon-smartphone":                         @"\uf034",
             @"icon-connected_object":                   @"\uf035",
             @"icon-lock":                               @"\uF512",
             @"icon-unlock":                             @"\uF513",
             @"icon-camera":                             @"\uF4F7",
             @"icon-isight":                             @"\uf039",
             @"icon-video_camera":                       @"\uf03a",
             @"icon-random":                             @"\uf03b",
             @"icon-message":                            @"\uF4AC",
             @"icon-discussion":                         @"\uf03d",
             @"icon-calendar":                           @"\uF4C5",
             @"icon-ringbell":                           @"\uf03f",
             @"icon-movie":                              @"\uf040",
             @"icon-mail":                               @"\u2709",
             @"icon-pen":                                @"\u270F",
             @"icon-settings":                           @"\u9881",
             @"icon-measure":                            @"\uf044",
             @"icon-vector":                             @"\uf045",
             @"icon-vector_pen":                         @"\u2712",
             @"icon-mute_on":                            @"\uf047",
             @"icon-mute_off":                           @"\uf048",
             @"icon-home":                               @"\u2302",
             @"icon-sheet":                              @"\uf04a",
             @"icon-arrow_big_right":                    @"\u21C9",
             @"icon-arrow_big_left":                     @"\u21C7",
             @"icon-arrow_big_down":                     @"\u21CA",
             @"icon-arrow_big_up":                       @"\u21C8",
             @"icon-dribbble_circle":                    @"\uf04f",
             @"icon-dribbble":                           @"\uf050",
             @"icon-facebook_circle":                    @"\uf051",
             @"icon-facebook":                           @"\uf052",
             @"icon-git_circle_alt":                     @"\uf053",
             @"icon-git_circle":                         @"\uf054",
             @"icon-git":                                @"\uf055",
             @"icon-octopus":                            @"\uf056",
             @"icon-twitter_circle":                     @"\uf057",
             @"icon-twitter":                            @"\uf058",
             @"icon-google_plus_circle":                 @"\uf059",
             @"icon-google_plus":                        @"\uf05a",
             @"icon-linked_in_circle":                   @"\uf05b",
             @"icon-linked_in":                          @"\uf05c",
             @"icon-instagram":                          @"\uf05d",
             @"icon-instagram_circle":                   @"\uf05e",
             @"icon-mfg_icon":                           @"\uf05f",
             @"icon-xing":                               @"\uF532",
             @"icon-xing_circle":                        @"\uF533",
             @"icon-mfg_icon_circle":                    @"\uf060",
             @"icon-user":                               @"\uf061",
             @"icon-user_male":                          @"\uf062",
             @"icon-user_female":                        @"\uf063",
             @"icon-users":                              @"\uf064",
             @"icon-file_open":                          @"\uF4C2",
             @"icon-file_close":                         @"\uf067",
             @"icon-file_alt":                           @"\uf068",
             @"icon-file_close_alt":                     @"\uf069",
             @"icon-attachment":                         @"\uf06a",
             @"icon-check":                              @"\u2713",
             @"icon-cross_mark":                         @"\u274C",
             @"icon-cancel_circle":                      @"\uF06E",
             @"icon-check_circle":                       @"\uf06d",
             @"icon-magnifying":                         @"\uF50D",
             @"icon-inbox":                              @"\uf070",
             @"icon-clock":                              @"\u23F2",
             @"icon-stopwatch":                          @"\u23F1",
             @"icon-hourglass":                          @"\u231B",
             @"icon-trophy":                             @"\uf074",
             @"icon-unlock_alt":                         @"\uF075",
             @"icon-lock_alt":                           @"\uF510",
             @"icon-arrow_doubled_right":                @"\u21D2",
             @"icon-arrow_doubled_left":                 @"\u21D0",
             @"icon-arrow_doubled_down":                 @"\u21D3",
             @"icon-arrow_doubled_up":                   @"\u21D1",
             @"icon-link":                               @"\uf07B",
             @"icon-warning":                            @"\u2757",
             @"icon-warning_alt":                        @"\u2755",
             @"icon-magnifying_plus":                    @"\uf07E",
             @"icon-magnifying_minus":                   @"\uf07F",
             @"icon-white_question":                     @"\u2754",
             @"icon-black_question":                     @"\u2753",
             @"icon-stop":                               @"\uf080",
             @"icon-share":                              @"\uf081",
             @"icon-eye":                                @"\uf082",
             @"icon-trash_can":                          @"\uf083",
             @"icon-hard_drive":                         @"\uf084",
             @"icon-information_black":                  @"\uf085",
             @"icon-information_white":                  @"\uf086",
             @"icon-printer":                            @"\uf087",
             @"icon-letter":                             @"\uf088",
             @"icon-soundcloud":                         @"\uf089",
             @"icon-soundcloud_circle":                  @"\uf08A",
             @"icon-anchor":                             @"\u2693",
             @"icon-female_sign":                        @"\u2640",
             @"icon-male_sign":                          @"\u2642",
             @"icon-joystick":                           @"\uF514",
             @"icon-high_voltage":                       @"\u26A1",
             @"icon-fire":                               @"\uF525",
             @"icon-newspaper":                          @"\uF4F0",
             @"icon-chart":                              @"\uF526",
             @"icon-spread":                             @"\uF527",
             @"icon-spinner_1":                          @"\uF528",
             @"icon-spinner_2":                          @"\uF529",
             @"icon-chart_alt":                          @"\uF530",
             @"icon-label":                              @"\uF531",
             @"icon-brush":                              @"\uE000",
             @"icon-refresh":                            @"\uE001",
             @"icon-node":                               @"\uE002",
             @"icon-node_2":                             @"\uE003",
             @"icon-node_3":                             @"\uE004",
             @"icon-link_2_nodes":                       @"\uE005",
             @"icon-link_3_nodes":                       @"\uE006",
             @"icon-link_loop_nodes":                    @"\uE007",
             @"icon-node_size":                          @"\uE008",
             @"icon-node_color":                         @"\uE009",
             @"icon-layout_directed":                    @"\uE010",
             @"icon-layout_radial":                      @"\uE011",
             @"icon-layout_hierarchical":                @"\uE012",
             @"icon-node_link_direction":                @"\uE013",
             @"icon-node_link_short_path":               @"\uE014",
             @"icon-node_cluster":                       @"\uE015",
             @"icon-display_graph":                      @"\uE016",
             @"icon-node_link_weight":                   @"\uE017",
             @"icon-more_node_links":                    @"\uE018",
             @"icon-node_shape":                         @"\uE00A",
             @"icon-node_icon":                          @"\uE00B",
             @"icon-node_text":                          @"\uE00C",
             @"icon-node_link_text":                     @"\uE00D",
             @"icon-node_link_color":                    @"\uE00E",
             @"icon-node_link_shape":                    @"\uE00F",
             @"icon-credit_card":                        @"\uF4B3",
             @"icon-disconnect":                         @"\uF534",
             @"icon-graph":                              @"\uF535",
             @"icon-new_user":                           @"\uF536",
             };
}

@end
