#import "IFOpenWebIcons.h"

@implementation IFOpenWebIcons

+ (NSURL *)fontFileURL
{
    return [[[NSBundle mainBundle] resourceURL] URLByAppendingPathComponent:@"openwebicons.ttf"];
}

+ (NSString *)fontName
{
    return @"OpenWeb Icons";
}

+ (NSDictionary *)allIcons
{
    return @{
             @"openwebicons-apml":                       @"\uf001",
             @"openwebicons-open-share":                 @"\uf00E",
             @"openwebicons-open-share-simple":          @"\uf00F",
             @"openwebicons-share":                      @"\uf006",
             @"openwebicons-share-simple":               @"\uf007",
             @"openwebicons-feed":                       @"\uf009",
             @"openwebicons-feed-simple":                @"\uf00A",
             @"openwebicons-ostatus":                    @"\uf004",
             @"openwebicons-ostatus-simple":             @"\uf005",
             @"openwebicons-opml":                       @"\uf003",
             @"openwebicons-activity":                   @"\uf010",
             @"openwebicons-activity-simple":            @"\uf041",
             @"openwebicons-microformats":               @"\uf00C",
             @"openwebicons-geo":                        @"\uf00B",
             @"openwebicons-opensearch":                 @"\uf002",
             @"openwebicons-oauth":                      @"\uf008",
             @"openwebicons-openid":                     @"\uf00D",
             @"openwebicons-semantic-web":               @"\uf000",
             @"openwebicons-rdf":                        @"\uf039",
             @"openwebicons-rdfa":                       @"\uf039",
             @"openwebicons-owl":                        @"\uf039",
             @"openwebicons-dataportability":            @"\uf013",
             @"openwebicons-federated":                  @"\uf011",
             @"openwebicons-web-intents":                @"\uf014",
             @"openwebicons-open-web":                   @"\uf012",
             @"openwebicons-xmpp":                       @"\uf015",
             @"openwebicons-html5":                      @"\uf016",
             @"openwebicons-css3":                       @"\uf017",
             @"openwebicons-connectivity":               @"\uf018",
             @"openwebicons-semantics":                  @"\uf019",
             @"openwebicons-3deffects":                  @"\uf037",
             @"openwebicons-device-access":              @"\uf031",
             @"openwebicons-multimedia":                 @"\uf032",
             @"openwebicons-offline-storage":            @"\uf033",
             @"openwebicons-perfintegration":            @"\uf034",
             @"openwebicons-git":                        @"\uf035",
             @"openwebicons-webhooks":                   @"\uf036",
             @"openwebicons-osi":                        @"\uf038",
             @"openwebicons-opensource":                 @"\uf038",
             @"openwebicons-opengraph":                  @"\uf020",
             @"openwebicons-epub":                       @"\uf021",
             @"openwebicons-qr":                         @"\uf022",
             @"openwebicons-foaf":                       @"\uf023",
             @"openwebicons-info-card":                  @"\uf024",
             @"openwebicons-browserid":                  @"\uf025",
             @"openwebicons-remote-storage":             @"\uf026",
             @"openwebicons-persona":                    @"\uf027",
             @"openwebicons-odata":                      @"\uf028",
             @"openwebicons-markdown":                   @"\uf029",
             @"openwebicons-tosdr":                      @"\uf030",
             @"openwebicons-pub":                        @"\uf045",
             @"openwebicons-sub":                        @"\uf046",
             @"openwebicons-hubbub":                     @"\uf045",
             @"openwebicons-pubsubhubbub":               @"\uf047",
             @"openwebicons-cc":                         @"\uf080",
             @"openwebicons-cc-by":                      @"\uf081",
             @"openwebicons-cc-nc":                      @"\uf082",
             @"openwebicons-cc-nc-eu":                   @"\uf083",
             @"openwebicons-cc-nc-jp":                   @"\uf084",
             @"openwebicons-cc-sa":                      @"\uf085",
             @"openwebicons-cc-nd":                      @"\uf086",
             @"openwebicons-cc-public":                  @"\uf087",
             @"openwebicons-cc-zero":                    @"\uf088",
             @"openwebicons-cc-share":                   @"\uf089",
             @"openwebicons-cc-remix":                   @"\uf08a",
             @"openwebicons-hatom":                      @"\uf040",
             @"openwebicons-hresume":                    @"\uf042",
             @"openwebicons-hcard-add":                  @"\uf043",
             @"openwebicons-hcard-download":             @"\uf044",
             @"openwebicons-indieweb":                   @"\uf08b",
             @"openwebicons-indiewebcamp":               @"\uf08b",
             @"openwebicons-webfinger":                  @"\uf08e",
             @"openwebicons-bitcoin":                    @"\uf08f",
             @"openwebicons-bitcoin-simple":             @"\uf090",
             @"openwebicons-svg":                        @"\uf049",
             @"openwebicons-json-ld":                    @"\uf048",
             @"openwebicons-tent":                       @"\uf050",
             @"openwebicons-copyleft":                   @"\uf051",
             @"openwebicons-gnu":                        @"\uf052",
             @"openwebicons-ofl-attribution":            @"\uf081",
             @"openwebicons-ofl-share":                  @"\uf085",
             @"openwebicons-ofl-renaming":               @"\uf04a",
             @"openwebicons-ofl-selling":                @"\uf04b",
             @"openwebicons-ofl-embedding":              @"\uf04c",
             @"openwebicons-webmention":                 @"\uf04d",
             @"openwebicons-javascript":                 @"\uf04e",
             @"openwebicons-wtfpl":                      @"\uf04f",
             @"openwebicons-ofl":                        @"\uf053",
             @"openwebicons-wordpress":                  @"\uf054",
             @"openwebicons-owncloud":                   @"\uf055",
             @"openwebicons-cccs":                       @"\uf056",
             @"openwebicons-barcamp":                    @"\uf057",
             @"openwebicons-indiehosters":               @"\uf058",
             @"openwebicons-known":                      @"\uf059",
             @"openwebicons-mozilla":                    @"\uf05a",
             @"openwebicons-unhosted":                   @"\uf05b",
             @"openwebicons-diaspora":                   @"\uf05c",
             @"openwebicons-indie":                      @"\uf05d",
             @"openwebicons-ghost":                      @"\uf05e",
             @"openwebicons-webplattform":               @"\uf05f",
             @"openwebicons-opensourcedesign":           @"\uf060",
             @"openwebicons-opendesign":                 @"\uf061",
             @"openwebicons-gnusocial":                  @"\uf062",
             @"openwebicons-gnusocial-simple":           @"\uf063",
             };
}

@end
