#import "IFZocialButtons.h"

@implementation IFZocialButtons

+ (NSURL *)fontFileURL
{
    return [[[NSBundle mainBundle] resourceURL] URLByAppendingPathComponent:@"zocial.ttf"];
}

+ (NSDictionary *)allIcons
{
    return @{
             @"zocial.acrobat":                          @"\uf100",
             @"zocial.amazon":                           @"\uf101",
             @"zocial.android":                          @"\uf102",
             @"zocial.angellist":                        @"\uf103",
             @"zocial.aol":                              @"\uf104",
             @"zocial.appnet":                           @"\uf105",
             @"zocial.appstore":                         @"\uf106",
             @"zocial.bitbucket":                        @"\uf107",
             @"zocial.bitcoin":                          @"\uf108",
             @"zocial.blogger":                          @"\uf109",
             @"zocial.buffer":                           @"\uf10a",
             @"zocial.cal":                              @"\uf10b",
             @"zocial.call":                             @"\uf10c",
             @"zocial.cart":                             @"\uf10d",
             @"zocial.chrome":                           @"\uf10e",
             @"zocial.cloudapp":                         @"\uf10f",
             @"zocial.creativecommons":                  @"\uf110",
             @"zocial.delicious":                        @"\uf111",
             @"zocial.digg":                             @"\uf112",
             @"zocial.disqus":                           @"\uf113",
             @"zocial.dribbble":                         @"\uf114",
             @"zocial.dropbox":                          @"\uf115",
             @"zocial.drupal":                           @"\uf116",
             @"zocial.dwolla":                           @"\uf118",
             @"zocial.email":                            @"\uf119",
             @"zocial.eventasaurus":                     @"\uf11a",
             @"zocial.eventbrite":                       @"\uf11b",
             @"zocial.eventful":                         @"\uf11c",
             @"zocial.evernote":                         @"\uf11d",
             @"zocial.facebook":                         @"\uf11e",
             @"zocial.fivehundredpx":                    @"\uf11f",
             @"zocial.flattr":                           @"\uf120",
             @"zocial.flickr":                           @"\uf121",
             @"zocial.forrst":                           @"\uf122",
             @"zocial.foursquare":                       @"\uf123",
             @"zocial.github":                           @"\uf124",
             @"zocial.gmail":                            @"\uf125",
             @"zocial.google":                           @"\uf126",
             @"zocial.googleplay":                       @"\uf127",
             @"zocial.googleplus":                       @"\uf128",
             @"zocial.gowalla":                          @"\uf129",
             @"zocial.grooveshark":                      @"\uf12a",
             @"zocial.guest":                            @"\uf12b",
             @"zocial.html5":                            @"\uf12c",
             @"zocial.ie":                               @"\uf12d",
             @"zocial.instagram":                        @"\uf12e",
             @"zocial.instapaper":                       @"\uf12f",
             @"zocial.intensedebate":                    @"\uf130",
             @"zocial.itunes":                           @"\uf131",
             @"zocial.joinme":                           @"\uf165",
             @"zocial.klout":                            @"\uf132",
             @"zocial.lanyrd":                           @"\uf133",
             @"zocial.lastfm":                           @"\uf134",
             @"zocial.lego":                             @"\uf135",
             @"zocial.linkedin":                         @"\uf136",
             @"zocial.lkdto":                            @"\uf137",
             @"zocial.logmein":                          @"\uf138",
             @"zocial.macstore":                         @"\uf139",
             @"zocial.meetup":                           @"\uf13a",
             @"zocial.myspace":                          @"\uf13b",
             @"zocial.ninetyninedesigns":                @"\uf13c",
             @"zocial.openid":                           @"\uf13d",
             @"zocial.opentable":                        @"\uf13e",
             @"zocial.paypal":                           @"\uf13f",
             @"zocial.persona":                          @"\uf164",
             @"zocial.pinboard":                         @"\uf140",
             @"zocial.pinterest":                        @"\uf141",
             @"zocial.plancast":                         @"\uf142",
             @"zocial.plurk":                            @"\uf143",
             @"zocial.pocket":                           @"\uf144",
             @"zocial.podcast":                          @"\uf145",
             @"zocial.posterous":                        @"\uf146",
             @"zocial.print":                            @"\uf147",
             @"zocial.quora":                            @"\uf148",
             @"zocial.reddit":                           @"\uf149",
             @"zocial.rss":                              @"\uf14a",
             @"zocial.scribd":                           @"\uf14b",
             @"zocial.skype":                            @"\uf14c",
             @"zocial.smashing":                         @"\uf14d",
             @"zocial.songkick":                         @"\uf14e",
             @"zocial.soundcloud":                       @"\uf14f",
             @"zocial.spotify":                          @"\uf150",
             @"zocial.stackoverflow":                    @"\uf151",
             @"zocial.statusnet":                        @"\uf152",
             @"zocial.steam":                            @"\uf153",
             @"zocial.stripe":                           @"\uf154",
             @"zocial.stumbleupon":                      @"\uf155",
             @"zocial.tumblr":                           @"\uf156",
             @"zocial.twitch":                           @"\uf166",
             @"zocial.twitter":                          @"\uf157",
             @"zocial.viadeo":                           @"\uf158",
             @"zocial.vimeo":                            @"\uf159",
             @"zocial.vk":                               @"\uf15a",
             @"zocial.weibo":                            @"\uf15b",
             @"zocial.wikipedia":                        @"\uf15c",
             @"zocial.windows":                          @"\uf15d",
             @"zocial.wordpress":                        @"\uf15e",
             @"zocial.xing":                             @"\uf15f",
             @"zocial.yahoo":                            @"\uf160",
             @"zocial.ycombinator":                      @"\uf161",
             @"zocial.yelp":                             @"\uf162",
             @"zocial.youtube":                          @"\uf163",
             };
}

@end
